### ISSUE TITLE
Mobil App does not show my feedback

### ISSUE THREAD

**Issue by Hester555** [warmshowers/Warmshowers.org#1030]
Hello WS  github.
My mobile profile shoes NO feedback. I have over 100 feedback on website! This has strongly affected my request rate in 2018 and I miss my riders.  I am a big fan, have BEST feedback but since the redesign I am cut off from mobile users. One rider  said he "took a chance" when he saw I had no feedback. When he look at the website using a browser he was astonished.Please fix this for me. Hester555 on Warm showers website.
Rita Hester

**Comment by jackturner7678** [comment]
The Mobil apps are no longer supported.  Please use the main site with your Mobil internet browser.  The main site is now smartphone friendly.

**Comment by Hester555** [comment]
THanks Jack, but many cyclists use the app when they are traveling. Please see next thread. Sorry I posted twice I am going to close this thread and continue on the other one.
