### ISSUE TITLE
Odd wording (still) on recommendations on other users profile

### ISSUE THREAD

**Issue by chrisarusso** [warmshowers/Warmshowers.org#130]
To me the "Recommendations" and "I recommend" are not clear when you're viewing someone else's profile page.

Maybe "Users who recommend @name" and "Users @name recommends"

or 
 
"Recommendations given" vs "Recommendations received"
 
or

Maybe just one tab "Recommendations" and go back to the page that has both on it?

Thoughts?
What's a good comparison of an established site that has a "recommendation" block.  ... Checking couchsurfing...

**Comment by kalpaitch** [comment]
No longer relevant.
