### ISSUE TITLE
Change Brazilian flag for Portuguese/Brazilian flag

### ISSUE THREAD

**Issue by martinmemartin** [warmshowers/Warmshowers.org#153]
Geoffroy de Lavareille contacted WS, 2012 07 10, regarding the Brazilian flag signifying Portuguese language version of the site. He suggested it would make more sense to use the Portuguese flag.
Gonçalo suggested to implement a flag showing both the Portuguese and the Brasil flag, both of them split.

**Comment by rfay** [comment]
At this point, we have no flags, so closing this for now.
