### ISSUE TITLE
 Edit profile: State/Province drop-down menu not listing provinces

### ISSUE THREAD

**Issue by martinmemartin** [warmshowers/Warmshowers.org#161]
Warmshowers user vagamonde.net posted the following at the Warmshowers forum "Redesign questions and answers" on 2012 July 21:

Edit profile: State/Province drop-down menu not listing provinces

I am just checking out the new look of the site. Very nice. However, I had a bit of a problem updating my profile, in particular in changing my address. At first try, the State/Province drop-down menu only had "NOT LISTED" as an option. Choosing that, I was able to save my updates. Then, I went back to edit, and the province list was there as it should be. Bug?

**Comment by rfay** [comment]
OK @kalpaitch  - feel free to take a look at this. It just needs a standard D7 #ajax fix. Both Chris and I will be ever so glad to see it work.

**Comment by rfay** [comment]
I should mention, @kalpaitch if it matters. I was deeply involved in the D7 improvements to #ajax and wrote the examples in the Examples module and blogged about them at randyfay.com. So theoretically I can get that back into my head and solve this quickly when I get to it. However, I have no sense that I have to be the one to work on it, and if #ajax sounds fun to you, that's very cool. I just want to put this one to bed after years. It should much easier with the new framework. As far as combining with field-ifying user_location, it has some problems, as I mentioned - Many many hard-to-replace queries which would have to be done over with EFQs... but combined with wsuser fields which are not yet fields, etc. Some possible performance concerns. Complex proximity queries.

**Comment by rfay** [comment]
Taking this back for now, based on the above. I'm at that point in my wsuser checklist, and just fixed another #ahah to #ajax change, so it seems natural. Hope I'm not stepping on any toes.
