### ISSUE TITLE
Translate text generated by rules (or stop doing it with rules)

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#187]
We have a couple of email messages that are handled by rules (and login messages). They're currently done in English only.

1. Why did you delete your account?
2. Member recommendation emails
3. [Unvalidated user login message](http://www.warmshowers.org/admin/rules/rules/rules_redirect_to_unvalidated_info_page_on_unvalidated_user_login/edit)

We should probably try to figure out how to translate these.

Background on this general problem, along with some possible hints, is provided at http://drupal.org/node/755140. It points to a couple of off-drupal modules that might conceivably help.

We could also just code this stuff and stop using rules for these tasks.

**Comment by rfay** [comment]
@CyrilWendl it looks like we can translate D7 rules, so yay, we can finally get this one in!

**Comment by rfay** [comment]
The issue in rules is https://www.drupal.org/node/1356982

**Comment by CyrilWendl** [comment]
Perfect! So, we will have to figure out how to use this.

**Comment by rfay** [comment]
These are now on the list in #927
