### ISSUE TITLE
Redirection problem on replies in forums for translated pages

### ISSUE THREAD

**Issue by miklagard** [warmshowers/Warmshowers.org#286]
On Turkish WarmShoweres page, while answering by reply on forum threads, it redirects from tr.warmshowers.org to www.warmshowers.org.

**Comment by rfay** [comment]
I think this one may be solved by the fact that we now require all forum posts to be language-neutral.

**Comment by rfay** [comment]
I think this should be solved now, please reopen if you see this again.
