### ISSUE TITLE
Bad place Icons showing in Farsi interface

### ISSUE THREAD

**Issue by amir3** [warmshowers/Warmshowers.org#295]
In Farsi (a right-to-left) module we have some problem for displaying some blocks in inappropriate positions. 

(Follow links to see images; makes it easier for @amir3 with slow internet access)

[problem7](https://f.cloud.github.com/assets/3687007/400884/e38c3f80-a8c5-11e2-9bc7-f499425d730d.JPG)
[problem8](https://f.cloud.github.com/assets/3687007/400887/f4d6f816-a8c5-11e2-9124-afe50c8e747a.jpg)

**Comment by rfay** [comment]
Closing this for when the new Farsi translator approaches it, as it's probably invalidated by the new theme and D7
