### ISSUE TITLE
Switch core Drupal code to Pressflow

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#350]
I've been tempted to do this many times, but noticed while doing some xhprof poking around some pretty silly things that will never be fixed in D6.  Most of them (including, I think, the single core patch we currently apply) could be resolved by moving to [Pressflow](https://github.com/pressflow/6). Mostly, we spend 50ms on every request looking up the node of the current URL. Yes, amazing. It does a select COUNT() from the url_alias table in [drupal_lookup_path()](https://github.com/warmshowers/Warmshowers.org/blob/site/includes/path.inc#L53-55). Every time. 

```
  if (!isset($count)) {
    $count = db_result(db_query('SELECT COUNT(pid) FROM {url_alias}'));
  }
```
I don't *think* this is any harder than a normal minor version update, but there might be some gotcha in config or something. Probably worth the move.

**Comment by kalpaitch** [comment]
No longer relevant.
