### ISSUE TITLE
Links on start page too big

### ISSUE THREAD

**Issue by CyrilWendl** [warmshowers/Warmshowers.org#373]
In several languages (Polish and Russian) the links in the member box of the default WS page overlap the box. Here is what I see in Polish:

![capture](https://f.cloud.github.com/assets/2380893/1863640/13339842-77e6-11e3-857f-8f687ba070eb.PNG)

I guess the CSS should be changed as follows:

![css](https://f.cloud.github.com/assets/2380893/1863642/15356bf2-77e6-11e3-8b8b-853978474a6c.png)

It might bot be a good idea however to change the CSS for every language separately, for in case the text changes, the CSS has to be altered anew. I'd rather propose a font in relative size to the box proportions. One should figure out how to do this with CSS, if possible after all.

**Comment by rfay** [comment]
This was fixed with a little bit of css_injector magic, so is no longer a problem.
