### ISSUE TITLE
Consider removing scheduler module and using another technique to manage unpublishing

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#376]
During the forum management push in 2013 I installed scheduler module and configured it to unpublish forum posts after a year. I think this is going to end up biting us, and we should just consider turning it off now.

**Comment by rfay** [comment]
I turned it off today; we probably do need something for this. But this was awkward (and I'm not sure it worked at all)

**Comment by kalpaitch** [comment]
I don't understand the reasoning for un-publishing posts. No longer relevant.
