### ISSUE TITLE
Ensure translation quality: verifiers in each language

### ISSUE THREAD

**Issue by CyrilWendl** [warmshowers/Warmshowers.org#385]
Russian translator Alexander who recently took over the translation from Lola told me the translation seemed to be partially in bad Russian.
I've had my doubts several times concerning the quality of the translations because I can't understand most of the languages.
What do you propose? A possibility would be to just mention a "translation quality verifier" on the volunteer opportunities page.

**Comment by rfay** [comment]
Cyril has implemented this.
