### ISSUE TITLE
Suggested annual donation, better donation handling, membership levels 

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#417]
Suggested annual donation ideas:

1. $10 (suggested) per year. Can be skipped
2. Donor badge on profile for those who give (different levels of membership?)
3. Request on sign up (or just after) and anniversary of signup
4. Say what the money is used for
5. Make sure current donors are properly acknowledged and credited for their donations

Questions:
Is a d7 upgrade a prerequisite? 

It looks to me like this could be cobbled together pretty well using "donor" as a role, using role_expire or rules to remove the role after a year or whatever. 

Money can be accepted and noted with:
https://www.drupal.org/project/pay
https://www.drupal.org/project/paypal (or https://www.drupal.org/project/lm_paypal ?)
https://www.drupal.org/project/donate

**Comment by rfay** [comment]
Reviewed lm_paypal, which looked to be of more recent vintage, but shockingly it can't handle above 16-bit UIDs, which we're way past. Amazing, https://www.drupal.org/node/502394 - so it's out unless we want to unwind that bug for them.

**Comment by rfay** [comment]
Took another look at [paypal](http://drupal.org/project/paypal) + pay + donate, and again skunked. It's not in a position where the maintainer can basically recommend using it for anything.

So AFAIK the only module suite from drupal.org that would be reliable would be Ubercart. I dearly hate the idea of implementing all of ubercart just for membership/donations. Maybe it's what should be done.

**Comment by rfay** [comment]
@illmasterc  recommended Stripe based on successful experience and pointed me to the custom module he's using for a client, https://github.com/illmasterc/Tilthy-Rich-Compost-Website/tree/master/drupalroot/sites/all/modules/custom/stripe_integration

Ubercart also has uc_stripe, looks maintained. And there are Stripe drupal modules.

**Comment by rfay** [comment]
This is live and up there and we'll do followups in new issues.

**Comment by illmasterc** [comment]
Woo hoo :fireworks: :sparkle: :sparkler: :sparkles: :sparkling_heart:
