### ISSUE TITLE
Drupal 7/8/Backdrop Upgrade for Warmshowers.org

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#429]
Sadly, we'll eventually be pushed to a Drupal 7 (or possibly Backdrop CMS: http://backdropcms.org/). Upgrading to Drupal 8 is also possible, but it would require waiting until lots of modules mature in Drupal 8. (But there is supposed to be a direct migration path from D6 to D8)

The things that are pushing us now:

1. Drupal 6 support will end shortly after Drupal 8 comes out, probably in several months.
2. PHP 5.3 support has already ended, and Drupal 6 can't really run on a newer PHP. 
3. Modules for Drupal 6 are rarely being maintained at this point, so we end up with possible security problems and with far fewer options for problemsolving.

This is a huge job. It's been a huge job when we did it in the past. It is in fact blocking us on lots of things though. I think we'll want to consider paying for development work on this.

In addition, our theme will need to be updated, and of course we might want to refresh it in the process.

**Comment by rfay** [comment]
I've spent some time evaluating other options, including learning some python and trying out django and django-cms. Of course I'm overwhelmed by what a Drupal developer doesn't know about another platform, and also the multitude of things that we "just know how to do" in Drupal that we have no idea whether will work or have to be developed for another platform.

My bet is that we'll end up moving (probably next year) to mature Drupal 7, then waiting to decide between Backdrop and Drupal 8 a few years later depending on how both of those work out. In theory Backdrop would be by far the best for us, but it's not clear how much support there will be. But some time will tell.

**Comment by kalpaitch** [comment]
Closing as no longer relevant, can evaluate upgrade options in a few years.
