### ISSUE TITLE
Remove "Spam filters" page from site

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#470]
We tried to maintain a "Spam filters" page for some time.

@CyrilWendl  points out that it's old, poorly maintained, and useless for our international audience. It should be retired.

There are some links out there in various languages that can be used. Perhaps each translator can choose a link explaining things  in their own language.

**Comment by CyrilWendl** [comment]
I've now removed the reference to this in the signup page (if removed one sentence, and have kept the other instructions, which I still consider as helpful). Now, translators will just have to remove this sentence too, and I've created a point in the Google Spreadsheet for this. I hope that is fine with you.

**Comment by rfay** [comment]
Thanks, closing then.
