### ISSUE TITLE
Logout+username element floating on top of a photo

### ISSUE THREAD

**Issue by simison** [warmshowers/Warmshowers.org#474]
When I click open a photo attached to a reference, it opens into a modal just fine. On top of it I can see login-bar though. 

![image](https://cloud.githubusercontent.com/assets/87168/6494171/a7a7594e-c274-11e4-91b2-06ed49fc1405.png)

Just a simple css z-index issue.

With profile photo modal I don't notice the same.

Here; https://www.warmshowers.org/recommendation/feedback-mikael-1

**Comment by rfay** [comment]
Would love to see this fixed. Should be easy.

**Comment by kalpaitch** [comment]
Not relevant any more.
