### ISSUE TITLE
D7: Evaluate and update modules in "patched" directory

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#491]
sites/all/modules/patched has a number of modules that claim to be patched. We need to get them cleaned up or understand why there's a patch before the D7 upgrade begins.

1. Evaluate the patch and reason for the patch (if it's still patched)
2. Document as necessary, determine if D7 importance
3. Move into contrib if possible
4. Apply drush rr if necessary when deploying live

**Comment by chrisarusso** [comment]
Existing modules that require consideration: 

```
cck  contact  mailmime  persistent_login  role_delay  services
```

**Comment by chrisarusso** [comment]
CCK - @rfay 

I replaced the patched version of cck with the contrib version via: `drush dl cck-6.x-2.9` and get the following `git diff`
```
MacBook-Pro:patched chris$   git status
On branch site
Your branch is up-to-date with 'origin/site'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   cck/includes/content.token.inc

no changes added to commit (use "git add" and/or "git commit -a")
MacBook-Pro:patched chris$ git diff
diff --git a/docroot/sites/all/modules/patched/cck/includes/content.token.inc b/docroot/sites/all/modules/patched/cck/includes/content.token.inc
index f863e4e..c446e60 100644
--- a/docroot/sites/all/modules/patched/cck/includes/content.token.inc
+++ b/docroot/sites/all/modules/patched/cck/includes/content.token.inc
@@ -166,7 +166,6 @@ if (module_exists('userreference')) {
       $tokens['user reference']['link']  = t('Formatted HTML link to referenced user');
       $tokens['user reference']['path']  = t("Relative path alias to the referenced user.");
       $tokens['user reference']['url']  = t("Absolute path alias to the referenced user.");
-      $tokens['user reference']['mail'] = t('Referenced user email address');
 
       return $tokens;
     }
@@ -182,9 +181,6 @@ if (module_exists('userreference')) {
       $tokens['path'] = is_numeric($item['uid']) ? url('user/' . $item['uid']) : '';
       $tokens['url'] = is_numeric($item['uid']) ? url('user/' . $item['uid'], array('absolute' => TRUE)) : '';
 
-      $user = user_load(array('uid' => $item['uid']));
-      $tokens['mail'] = $user ? $user->mail : '';
-
       return $tokens;
     }
   }
```

Does that look right to you? Can we ignore this into D7?

**Comment by rfay** [comment]
Since we have no idea where this came from, and the code is completely different (in core) in D7, I believe we should ignore this.

But I don't know why we would insist on removing the [mail] token. Apparently only from userreference?

And we do use [mail] regularly when sending out mail.

**Comment by chrisarusso** [comment]
So:
- [] cck  (agreed to move forward with no patch)
- [] contact  (obsolete due to using privatemsg
- [] mailmime  (obsolete, unused, disabled on live site: via drush pml)
- [] persistent_login (patched per PR: #540)  
- [] role_delay  (@rfay's patch we were using got in for D7 - https://www.drupal.org/node/1804596#comment-8670451)
- [] services (patch got in, so should be all set here)

**Comment by chrisarusso** [comment]
@rfay all those checkboxes look checked to me, shall we close this one?

**Comment by rfay** [comment]
Yay, congrats and thanks!
