### ISSUE TITLE
D7: Port or replace ws_pm_email_notify

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#497]
ws_pm_email_notify is a fork of pm_email_notify module, a submodule of privatemsg.

It's quite probable that it didn't need to be forked and that its functionality can be implemented as hooks on an unmodified pm_email_notify (that same module still exists on the D7 7.x-1.x branch of privatemsg). 

The two key features of this module from our perspective:

1. Sending out email notifications that have response links and correct reply-to and other details
2. Handling incoming emails (via mandrill_incoming module)

Testing of mandrill incoming stuff is a little complicated, as it requires a publicly accessible port.  I [wrote an article about tunnelling external webservice call](http://randyfay.com/content/tunneling-http-debug-or-develop-external-webservice-call) when originally doing this stuff to explain how to set up a development and testing environment.

Prerequisite: [D7 version of mandrill_incoming](https://github.com/warmshowers/Warmshowers.org/issues/496).

**Comment by kostajh** [comment]
This is a diff of `pm_email_notify` with @rfay's forked version: https://gist.github.com/kostajh/98bb1b3ab2406482ec42

**Comment by kostajh** [comment]
@rfay my intuition is that it should be possible to implement your custom changes via form_alters and hooks, and if that isn't possible in a few small areas, we can submit patches upstream to the 7.x-1.x branch of `privatemsg` to implement hooks that would allow us to customize.

**Comment by rfay** [comment]
Going to go ahead and work on this one. The agreed (attempted) path is:

1. Do not fork pm_email_notify
2. Attempt to use alters to accomplish the WS-specific things.
