### ISSUE TITLE
D7 prep: Migrate css_injector and js_injector features into code

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#508]
We have some legacy things in css_injector and js_injector that would be way better in code, and that would make them obvious during the D7 upgrade as well. Move them to appropriate places in the code.

A couple of things here are not currently translatable (like js modifications to the donate page) so this process should also allow those to become translatable.

**Comment by kalpaitch** [comment]
Fixed with pr https://github.com/warmshowers/Warmshowers.org/pull/627
