### ISSUE TITLE
D7: Port uc_stripe to D7 (on Drupal.org)

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#509]
uc_stripe is how we accept credit card payments. Randy built the current PCI-compatible version for 6.x based on another's work. Now it will have to be updated to 7.x and Ubercart 7.x-3.x

**Comment by rfay** [comment]
@timstallmann do you have any work done on this? I'm about to get to this point, so if you have anything already in progress it would be appreciated if you could do a PR or something. Thanks!

**Comment by timstallmann** [comment]
Hey Randy! What I've got is on https://github.com/timstallmann/uc_stripe_d7, but I didn't get any further than during the sprint. I'd say it's about halfway there.

**Comment by rfay** [comment]
Thanks - I'll fork that then.

-Randy

**Comment by rfay** [comment]
This is now pushed to 7.x-2.x on https://drupal.org/project/uc_stripe.

@timstallmann your work did help me, thanks!
