### ISSUE TITLE
D7: Donation system reconfiguration and test

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#514]
Our upgrade to D7 will undoubtedly break lots of things and the donation system will have to be redeployed.  Focus should be on parity, it's not critical to make things better than they are, but we should be able to continue accepting donations. There is a whole donation-upgrade milestone with marked labels for later this fall.

- [x] Configuration of from: email for donation ack
- [x] Donate page buttons should say "donate", etc., not "Add to cart" (done manually! after completion, added to process)
- [x] Sort the products correct on the /donate page
- [x] NON-configuration of the donor "role renewal" email
- [x] Proper distinction of donor thank-you page when free or paid
- [x] Remove the "Review order" step
- [x] Make sure it says "donation" instead of "order"
- [x] Test paypal (and paypal IPN success, order completion)
- [x] Donation complete page (cart/checkout/complete - thank you) has an invalid token in the message, so user ends up at the wrong place.
- [x] Check correct role expiration
- [x] Remove donation-free role when they do a paid donation. (This is for later)
- [x] Test recurring donations for correctness
- [x] Test an upgraded recurring donation to see if it works out
- [x] Make sure donation status block shows correct situation ASAP (watch caching).
- [x] Make sure user has access to recurring fee cancellation
- [x] Make sure donation levels are properly labelled. Especially "Someday"
- [x] Can't submit free/someday order
- [x] Payments don't get processed when skipping review page
- [x] Donation email sent even if payment not completed
- [x] Do not send donation confirmation email to free signups
- [x] Donation/Membership level FAQ links broken because of FAQ module change

**Comment by rfay** [comment]
A shocking amount of this is working now that uc_stripe is ready. It is not fine-tuned, and some things will have to be pushed into features.

**Comment by kalpaitch** [comment]
All good now except there are some PHP warnings and notices on the donation page generated by the uc_attribute module. For any product that has attributes the uc_attribute module is trying to do some fancy stuff with the product $node->data property (this is triggered in this case by the add_to_cart views field handler. However, when this handler loads the node the $node->data property is already some unserialized array, not sure if this is a left over legacy of the old site, or just that it's not being unserialized properly. See below:

```
object(stdClass)[429]
  public 'vid' => string '95520' (length=5)
  public 'uid' => string '1' (length=1)
  public 'title' => string 'Supporter Donation Level' (length=24)
  public 'log' => string '' (length=0)
  public 'status' => string '1' (length=1)
  public 'comment' => string '0' (length=1)
  public 'promote' => string '1' (length=1)
  public 'sticky' => string '0' (length=1)
  public 'nid' => string '84249' (length=5)
  public 'type' => string 'product' (length=7)
  public 'language' => string 'en-working' (length=10)
  public 'created' => string '1422991292' (length=10)
  public 'changed' => string '1427486289' (length=10)
  public 'tnid' => string '0' (length=1)
  public 'translate' => string '0' (length=1)
  public 'revision_timestamp' => string '1427486289' (length=10)
  public 'revision_uid' => string '1' (length=1)
  public 'model' => string 'supporter_membership' (length=20)
  public 'list_price' => string '25.00000' (length=8)
  public 'cost' => string '0.00000' (length=7)
  public 'sell_price' => string '0.00000' (length=7)
  public 'weight' => string '0' (length=1)
  public 'weight_units' => string 'lb' (length=2)
  public 'length' => string '0' (length=1)
  public 'width' => string '0' (length=1)
  public 'height' => string '0' (length=1)
  public 'length_units' => string 'in' (length=2)
  public 'pkg_qty' => string '1' (length=1)
  public 'default_qty' => string '1' (length=1)
  public 'ordering' => string '0' (length=1)
  public 'shippable' => string '0' (length=1)
  public 'price' => string '0.00000' (length=7)
  public 'body' => 
    array (size=1)
      'und' => 
        array (size=1)
          0 => 
            array (size=5)
              ...
  public 'upload' => 
    array (size=0)
      empty
  public 'field_amount_description' => 
    array (size=1)
      'und' => 
        array (size=1)
          0 => 
            array (size=3)
              ...
  public 'field_product_weight' => 
    array (size=1)
      'und' => 
        array (size=1)
          0 => 
            array (size=1)
              ...
  public 'field_image_cache' => 
    array (size=0)
      empty
  public 'field_cart_button_label' => 
    array (size=0)
      empty
  public 'cid' => int 0
  public 'last_comment_timestamp' => string '1422991292' (length=10)
  public 'last_comment_name' => string '' (length=0)
  public 'last_comment_uid' => string '1' (length=1)
  public 'comment_count' => int 0
  public 'attributes' => 
    array (size=1)
      1 => 
        object(stdClass)[445]
          public 'aid' => string '1' (length=1)
          public 'name' => string 'Options' (length=7)
          public 'description' => string '' (length=0)
          public 'label' => string '<none>' (length=6)
          public 'default_option' => string '14' (length=2)
          public 'required' => string '0' (length=1)
          public 'ordering' => string '0' (length=1)
          public 'display' => string '2' (length=1)
          public 'nid' => string '84249' (length=5)
          public 'default_label' => string '<none>' (length=6)
          public 'default_ordering' => string '0' (length=1)
          public 'default_required' => string '1' (length=1)
          public 'default_display' => string '2' (length=1)
          public 'options' => 
            array (size=2)
              ...
  public 'name' => string 'rfay' (length=4)
  public 'picture' => string '106763' (length=6)
  public 'data' => string 'a:51:{s:5:"roles";a:1:{i:0;s:1:"2";}s:7:"contact";i:1;s:8:"fullname";s:9:"Randy Fay";s:21:"notcurrentlyavailable";i:1;s:12:"availability";s:0:"";s:10:"fax_number";s:0:"";s:11:"mobilephone";s:15:"+1 970.462.7450";s:9:"homephone";s:0:"";s:9:"workphone";s:0:"";s:18:"nearest_large_city";s:0:"";s:16:"preferred_notice";s:0:"";s:4:"cost";s:0:"";s:11:"maxcyclists";s:1:"4";s:5:"motel";s:0:"";s:10:"campground";s:0:"";s:8:"bikeshop";s:0:"";s:8:"comments";s:1543:"I'm the Webmaster of Warmshowers.org and now the Executi'... (length=3139)
```

**Comment by kalpaitch** [comment]
Doesn't seem to be impacting the actual checkout flow so I'm closing this ticket, with a note to look at resolving these issues as part of https://github.com/warmshowers/Warmshowers.org/issues/612

**Comment by rfay** [comment]
Key item, which I think requires action during deployment, is that the options on products have to be set to $0 cost, otherwise all purchases are doubled. (Basic is listed as $10, but costs $20). 

This is all in the options sub-tab of the product config, for example http://wsupg.dev/node/84338/edit/options - Each of the options should be set to a price of $0

**Comment by vortle86** [comment]
Donation confirmation emails for both member and admin seem to have some config issues - broken images? They all open with " images not displayed" message, but displaying images doesn't change the message.
![14fc80dc3f4bb43f](https://cloud.githubusercontent.com/assets/11068882/9838317/9e0debce-5a17-11e5-852b-6f3fef7ba83b.jpg)

**Comment by vortle86** [comment]
User should not receive a separate email about role assignment. 
![14fc80dc8aa01372](https://cloud.githubusercontent.com/assets/11068882/9838433/d1284b96-5a1a-11e5-98fc-8310c3796da4.jpg)

**Comment by vortle86** [comment]
Should the ubercart role system accept more than one role, or should the most recent role supercede? For example this user currently has both "donation-free" and "donation-maintainer" roles.
![image](https://cloud.githubusercontent.com/assets/11068882/9838474/a4bea7c0-5a1b-11e5-89b9-b386f59f3378.png)

**Comment by rfay** [comment]
I would like to see donation-free removed when they do a paid donation.
Added that to the running list here. Thanks! (What you see is current
behavior, but still...)

**Comment by rfay** [comment]
This one seems like it's working! Yay.
