### ISSUE TITLE
Use settings.local.php for site-specific configuration

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#519]
For longer than I'd like to admit (like the whole history of WS) we've placed site-specific stuff in the settings.php, instead of including a settings.local.php. Time to fix it. This can be fixed in D6 now before the D7 upgrade.

**Comment by kalpaitch** [comment]
Randy as far as I can see the settings.php is already looking for a local.settings.php file. Am I missing something?

**Comment by rfay** [comment]
Fun :) It got (appropriately) added to the settings we give out to devs
 but never to mine or production. So yeah! It's at least partway there.


Thanks,
-Randy

**Comment by rfay** [comment]
Fixed in site_d7
