### ISSUE TITLE
Re-implement user_delete and related functionality and overrides

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#520]
user_delete module is obsolete of course, so its usage in self- and admin- deletion should be reimplemented. Note that these are form-altered quite a bit to make it clear to people what is happening. 

warmshowers_site module has _warmshowers_site_alter_user_delete() which was in charge of this.

D7 of course has changed the name to "user cancel"

The key nuances here are:
* We try to warn the user that their feedback may be deleted
* Admin needs to have the option to delete *everything* (when deleting spammers)

So it's good to revisit how this works in the D6 and see what the actual user experience is, and consider how to fix that. Translation will definitely be broken.

**Comment by kalpaitch** [comment]
@rfay I'm assuming the wording of the button to "user cancel" isn't an issue. Where possible I'd prefer to leave it as default.

**Comment by rfay** [comment]
I like "Cancel Account" better so am fine with going with that.  As above, it impacts translations, but it's worth it. 

I hope that there is a D7 way to choose between deleting and not, because it's so important about feedback.

**Comment by kalpaitch** [comment]
@rfay I don't think this issue was referenced from my recent pull request. I believe this can now be closed following your merge.
