### ISSUE TITLE
Rework feedback views

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#525]
There are a few feedback views, and they appear to be pretty broken. We currently have one for feedback I've given, one for received, and then the one on the lower right of the profile page.

**Comment by kalpaitch** [comment]
Taking... if no one else is.

**Comment by kalpaitch** [comment]
Related to (incorporated into) https://github.com/warmshowers/Warmshowers.org/issues/528

**Comment by rfay** [comment]
Awesome. This is one of the most critical views as it's used 2 places on every profile (the feedback block, and the feedback page).  Super important, and a blocker for theming.

It's possible that using a D6 dev and upgrading views to 6.x-3.x would be a migration path for this view other than hand-recreation. But you'd need a local D6, let me know if you need it. 

I've only done one view so far (the feedback json view), and I just created it and then added it to the ws_d7_upgrade_feature module, and I think that's a workable technique.

However, with all these views note that there's years and cruft in them, so it's not critical to recreate every display, etc. With this one, if you just get the feedback page working and the feedback block it will be a huge win.

**Comment by kalpaitch** [comment]
BTW, I believe the above merge will have resolved this ticket. They will still have to be themed - https://github.com/warmshowers/Warmshowers.org/issues/498

**Comment by kalpaitch** [comment]
Still some work to do on this to make it enabled by default and to make sure no new translatable strings have been introduced.
