### ISSUE TITLE
RSS feed view

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#526]
Make sure our RSS feed is being done right; it's currently a view of content, and we have a header that says where it is.

**Comment by kalpaitch** [comment]
Also referencing #528 as the intention is to get all views in a nice revertible feature, including this one.

**Comment by rfay** [comment]
I'm thinking this issues was just adding the header that says where the feed is. It's always been a view.

**Comment by kalpaitch** [comment]
The aim of this is to have just one rss feed (served by views) on the site which is added to the html head and resides at rss.xml to overwrite the default drupal feed.
