### ISSUE TITLE
D7 Views Management

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#528]
It looks to me like too many of the views are damaged coming over to 7.x-3.x, and there is so much cruft in there anyway, stuff that really needs to be deleted.

It would be possible to update the site to 6.x-3.x, and this might be easier in more ways than one, but still all the admin views that depend on VBO would be broken, as it's completely different now. 

1. Delete (manually) cruft unused views on Warmshowers.org
2. Create a hook_update_N() to delete important views on update
3. Add admin_views module, which will provide a number of key administrative views.
4. Craft remaining replacement views and add to a d7 feature.

**Comment by kalpaitch** [comment]
Taking... unless someone else wants it.

**Comment by rfay** [comment]
Awesome. Although the admin views need to be done before deployment, this one is not a blocker for any other development. But admin/user/vbo and admin/content/vbo are so widely used in daily life these are blockers to deployment (but not development).

I've already added admin_views to the project as a starting place, and it's pretty useful. Adding some filters to it and the relationship to warmshowers fields would be getting us on the way.

As with all, there's years and cruft in the existing views, and I think mostly for starters we need the main admin views recreated

**Comment by kalpaitch** [comment]
Also referencing https://github.com/warmshowers/Warmshowers.org/issues/526 as the intention is to get all views in a nice revertible feature, including this one.

**Comment by kalpaitch** [comment]
Clarifying my current understanding of all views needed, superseded etc etc - https://docs.google.com/spreadsheets/d/1KBJNLsEm-69eMgzWHD1omQDW20p6MeoppPQKalxxw2g/edit#gid=0

**Comment by kalpaitch** [comment]
Remaining work is dependent on https://github.com/warmshowers/Warmshowers.org/issues/514

**Comment by kalpaitch** [comment]
Donations view requires no extra work.
