### ISSUE TITLE
Ongoing D7 Upgrade Checklist (and drush updb checklist)

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#531]
Below is the process for migration. It's a doozy.

**Comment by rfay** [comment]
Here is the actual process I've been using for this on local dev. I'm maintaining it as I learn new things and try it again.

* Enable pm_email_notify in D6, make sure related table gets set
* Disable contrib modules in D6, at least consider doing that instead of moving. (drush pml --pipe --no-core --type=module ==status=enabled)
* D6: drush pm-uninstall -y smart_ip advpoll fivestar admin_menu content_copy emfield features features_translations redesign_content_types redesign_block_settings redesign_system_level redesign_translation fe_block 
* Move db to new code
* cd sites/all && mv modules ..  #Completely removes contrib from update process so it can be done one at a time.
* drush updb -y # Does all core
* cd sites/all && mv ../modules . # puts them all back
* cd sites/all/modules && mv dev ../..
* drush pm-uninstall -y login_one_time smart_ip # update for it is broken
* drush en -y ctools flag
* cd sites/all/modules/contrib && mv i18n ../..  # Don't want to do any i18n yet

* drush vset theme_default zen
* drush updb -y
* drush en -y image user_reference
* CCK migrations: drush en -y content_migrate and then follow instructions
* Upgrade i18n following careful instructions in https://www.drupal.org/node/1113358
* Enable login_one_time
* Run drush updb with contrib/dev
* ??? Disable/uninstall/reinstall pm_email_notify ???
* drush en -y features ws_d7_upgrade_features ws_services warmshowers_site context privatemsg_services colorbox rest_server devel  views_json views_ui token comment_notify role_delay persistent_login nodeblock css_injector js_injector faqs facebook_oauth environment_indicator eva faq auto_nodetitle ws_privatemsg_services imageapi_gd markdown better_formats better_messages comment_notify contact_reply_to css_injector js_injector diff disablepwstrength donations_thermometer facebook_oauth imagecache_profiles faq inactive_user nodeblock pathauto persistent_login prepopulate role_delay translatableregions rules_ui rules_scheduler googleanalytics extlink jquery_update wysiwyg eva views_watchdog wsuser_fboauth member_feedback_views token_actions_extras contextual i18n_variable ws_pm_email_notify i18n_string privatemsg_filter rules_admin
* If dev: drush en -y reroute_email
* Fix rest server stuff at http://wsupg.dev/admin/structure/services/list/json/server - must enable privatemsg items
* drush fra '
* Re-save Better Messages at http://wsupg.dev/admin/config/user-interface/better-messages
* When ready (on production), free up the features so that translators can work.

**Comment by kalpaitch** [comment]
Removing compass install and watch steps because we don't want to be running these on prod.

**Comment by kalpaitch** [comment]
Tis not urgent, but @rfay can you explain the 3rd bullet above, why are you finding it necessary to un-install smart_ip and other modules before core update?

**Comment by rfay** [comment]
A few modules fail the upgrade and break it, and we don't even need their
upgrade path. Uninstalling before and reinstalling after works fine.

**Comment by rfay** [comment]
Key issues for next round:

- [ ] Attempt to leave advpoll (7.x-1.x) live
- [ ] Attempt to leave fivestar (7.x-1.x) live - it probably needs to be enabled

**Comment by rfay** [comment]
cron moved into #905 
feedback email rules into #904 
flag_actions into #903
