### ISSUE TITLE
Account edit should redirect to account view

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#533]
Edit: The nonfunctional D6 code was *not* removed in #532. It just stayed there and was nonfunctional.

The account edit save should redirect to the account view page, or at least it did in the D6 version. The nonfunctional D6 code was removed in #532 .

**Comment by kalpaitch** [comment]
@TODONE. https://github.com/warmshowers/Warmshowers.org/pull/597

**Comment by rfay** [comment]
#597 merged

**Comment by rfay** [comment]
The technique used in #597 (rules) is not appropriate, causes all kinds of side-effects. It turns out that this rules redirect happens *anytime* user_save happens. Not just when the user is saving an account using the browser. 

The particular case where I discovered it is on order completion.
