### ISSUE TITLE
Review and re-implement rules for D7

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#534]
We updated rules, triggers, actions for D7 - each needs to be reviewed for correctness. Triggers and actions should probably be converted to rules.

As of 2015-08-31 the following rules still must be created and tested, see https://www.warmshowers.org/admin/rules/trigger

- [x] Admin: Notification of comment requiring moderation (rules_rules_action_mail_rules_notify_on_comment_needing_moderation_4)
- [x] Admin: User self-deletion email (already working, [rule link](http://wsupg.dev/admin/config/workflow/rules/reaction/manage/rules_notify_on_user_self_deletion))
- [x] Admin: User deletion by admin (actually a user-block/disable) by admin ([link](http://wsupg.dev/admin/config/workflow/rules/reaction/manage/rules_admin_email_when_user_blocked)
- [x] Feedback notification email to sender and receiver
- [x] Request to member to say why they deleted their account (when deleting)
- [x] Admin: Check for negative feedback on deleted user - deferred, see #781
- [x] Login should redirect to dashboard. [rule link](http://wsupg.dev/admin/config/workflow/rules/reaction/manage/rules_redirect_to_dashboard_on_login)
- [x] Remove rules v1 rules from db (added hitting http://wsupg.dev/admin/config/workflow/rules/upgrade/clear to the migration procedure)

#711 is spun off for the daily admin emails

As far as I can tell we don't use triggers and actions any more.

**Comment by kalpaitch** [comment]
There is one rule which has a missing condition -
Error: Unknown condition uc_payment_condition_order_balance.

**Comment by rfay** [comment]
Ah, I edited that manually and never saved as a feature (when working on donation system locally). Thanks for pointing it out.

**Comment by kalpaitch** [comment]
Well all that needs to happen here is to export the uc_recurring_renewal_paid rule @rfay, absolutely no rush. Everything else is checked and reviewed.

**Comment by kalpaitch** [comment]
90% of all the rules are to send emails.

Here is a complete list of emails - https://docs.google.com/spreadsheets/d/1uasOTm03AgN9c_LV6etjFEm2O52h07qM5lbhuPgM6cw/edit#gid=0

Reviewed rules, custom mail sent through hook_mail and system wide mail.

**Comment by rfay** [comment]
Updated the list of outstanding rules in the O.P.
