### ISSUE TITLE
Review all emails in all languages for correctness, fix tokens

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#535]
All emails need to be reviewed

- Do they go out in the correct language?
- Is the formatting and token replacement correct?
- Token replacement: All [xxx] becomes [user:xxx]. This will need to be done across the board

Incomplete list of emails:

- Privatemsg notificaton
- Validation email
- Inactivity notice
- Set available notice "Now available to host"
- "Marked unavailable, update your return date"
- Donation acknowledgment
- Inactive User

**Comment by rfay** [comment]
I made huge progress on this by turning the emails into features and then search-and-replace. So this one is not a huge deal now, but will require careful review by the translators.

**Comment by rfay** [comment]
Sadly, I added all the fixed emails (with correct tokens) that are variable-based into the ws_d7_upgrade_features, but they aren't being retrieved from there. The database value is being used instead, not even the local value from D6. I confused how I could have exported them successfully, but can't now use them.

**Comment by kalpaitch** [comment]
Here is a complete list of emails - https://docs.google.com/spreadsheets/d/1uasOTm03AgN9c_LV6etjFEm2O52h07qM5lbhuPgM6cw/edit#gid=0

Reviewed rules, custom mail sent through hook_mail and system wide mail.

**Comment by rfay** [comment]
I think these are good. Adding this to the translator list in #581
