### ISSUE TITLE
Consider re-establishing a new salt value for D7 passwords

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#541]
Drupal 7 has added a salt value to make passwords harder to crack. 

We should probably use it explicitly; I'm not sure what happens to migrated D6 passwords, but this is worth checking.

**Comment by kalpaitch** [comment]
As far as I'm aware there is no way to migrate passwords. D7 doesn't even use md5.

So in the past we've used this as a good opportunity to bulk email all users and ask them to reset their passwords:
1) To improve the security of the site (most people appreciate this consideration at the slight inconvenience).
2) To filter out user accounts that just aren't used any more.

**Comment by rfay** [comment]
Well, passwords work fine after the upgrade, but IIRC it's a result of *not* using the salt on existing passwords. So since we're using the upgrade technique, we *have* working passwords.  But I don't think they're helped by the salt... not sure how that works.

We delete all users each calendar year who haven't been active for that year, after emailing them, so we don't get the real benefit there.

And unfortunately a large part of our membership is quite computer illiterate, so it's hard to throw things at them like this. I just asked everybody to add a photo to their profile last year and it created a support crisis :-)

But yeah, mass password reset may be the ticket.

**Comment by rfay** [comment]
I think this actually gets re-salted in the upgrade process.
