### ISSUE TITLE
Privatemsg services not currently available in D7 privatemsg

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#547]
Currently the Windows Phone app has private messaging implemented, and it's under active development for iOS. However, there is no D7 version of the Privatemsg Services module, which is required to access these.

As mentioned in #499 there is a readme in current ws_privatemsg_service module (forked) explaining why it was forked and what its history is.

[Stackexchange question](http://drupal.stackexchange.com/questions/79547/how-to-send-and-recieve-privatemsg-with-services-rest-in-drupal-7)
[Services Entity API](https://www.drupal.org/project/services_entity) would allow some access
[Issue about adding this in Privatemsg queue](https://www.drupal.org/node/433780)
[Privatemsg Services Sandbox](https://www.drupal.org/sandbox/deminy/2413647) of unknown quality and maturity

**Comment by kalpaitch** [comment]
This is why I prefer the RESTful module, it's so much more lightweight, flexible, and extensible. Not very helpful, but if we do have to rebuild all the service calls it might be worth a though. #thinkingoutloud.

**Comment by rfay** [comment]
I'm all in favor or RESTful instead of Services, but don't see how it pertains to this issue. There's no current RESTful support for privatemsg either is there?

**Comment by rfay** [comment]
I went ahead and did some basic testing on the sandbox, added a readme, and committed it. Followup work can go in #499 - I think it should involve enabling this, disabling that, and testing.
