### ISSUE TITLE
Imagecache to Styles migration

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#554]
Imagecache has changed to Styles in D7. We have to make images work as they did. The issue https://www.drupal.org/node/1316472 explains how to do this. There's even a module for it, but the module is not particularly pretty.

**Comment by kalpaitch** [comment]
Randy upgraded image cache presets, now they're added to features this ticket can be closed. https://github.com/warmshowers/Warmshowers.org/pull/624
