### ISSUE TITLE
Drupal 7 API Migration Issues for apps

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#555]
Hi wonderful app developers. 

There are five very important API changes forced on us by the upcoming Drupal 7 upgrade. 

1. A CSRF token has to be obtained from the server immediately after login, and then must be provided using the X-CSRF-Token header for each action taken. You'll get a 403 error if you do not provide it.  The token can be obtained from https://www.warmshowers.org/services/session/token - the flow is:
  * Log In
  * Get the token
  * In every following call, provide the header X-CSRF-Token as in:
     `X-CSRF-Token: KkSi6vREzVqx_M7Hso52z6u_J9rfKspUF7s3kwxYLZc`
2. The locations of user photos have changed. In the past we used the $account->picture or some combination of imagecache URLs with it. Now we have specific image URLs (full URLs) provided in the account JSON. 

  * $account-> profile_image_profile_picture is the URL to a 179x200 profile picture (as is used on the profile page on the site), for example https://www.warmshowers.org/files/imagecache/profile_picture/pictures/picture-1165.jpg
  * $account-> profile_image_mobile_profile_photo_std is a 400x400 profile picture, for example https://www.warmshowers.org/files/imagecache/mobile_profile_photo_std/pictures/picture-1165.jpg

3. Please use the [standard user GET](https://github.com/warmshowers/Warmshowers.org/wiki/Warmshowers-RESTful-Services-for-Mobile-Apps#userretrieve) instead of user/%/json, which has been deprecated for several months. I'd like it not to survive into the D7 migration.
These changes are already live on warmshowers.org (except that the CSRF Token is ignored when provided, and is not required). The android app is already able to hit both a D6 site and a D7 without major problems.
4. In services/rest/hosts_bylocation, please use the 'fullname' field for the user's full name and the 'name' field if you need the username. In the past the 'name' field returned the fullname; bug discovered by Chris Meyer, developer of iOS app.
5. Please make sure you're not using the obsolete contact_resource. This is so obsolete that it hasn't even been in the docs for a couple of years.

There is already a staging stie available where you can test against a D7 version, so please let me know if you need access to it. 

Thanks for updating your apps as soon as possible to deal with these changes. I hope to deploy Drupal 7 in September or October, so if we can get all our apps using these now, hopefully we won't have a bunch of broken app users at that time.

**Comment by rfay** [comment]
Removed from D7 upgrade, but leaving open for visibility to app developers.

**Comment by rfay** [comment]
I think all have now been upgraded. Thanks everybody!

**Comment by klzig** [comment]
FYI I'll have to do another turn of the WP app, to version 1.3.1.0.  I somehow missed the switch from name to fullname and the staging site still had the bug.  All else appears to be working as expected after the D7 upgrade.
