### ISSUE TITLE
php5-fpm lockup daily - serious system problem

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#562]
In the last several days we've been having many times where php5-fpm locks up and stops responding, taking the site offline. Log says `Jun 02 16:29:54 warmshowers php-fpm:  [WARNING] [pool www] server reached pm.max_children setting (75), consider raising it`. In the moments leading up to that we see lots of children being spawned in just a few seconds. After it happens it seems that all children are unresponsive.

The quick fix is

`sudo service php5-fpm restart`

### Diagnostics

* To see the php5-fpm status report, use /usr/local/bin/check_fpm - if it responds, note the status
* To see the php5-fpm status report via nginx, use curl localhost/status. If that doesn't work but the direct report does, it probably means something about nginx/php-fpm cooperation.

### Resources:
* [nginx forum on seeming exact problem](http://forum.nginx.org/read.php?3,224236,224236#msg-224236)

### Todo:
* Turn on php5-fpm slow log
* Make sure that mysql slow log is actually going to papertrail

### Things that have been done
* Set up a much larger set of children/workers
* Added monitoring on newrelic
* Changed config to recycle php5-fpm workers more often
* Added tracking of mysql slow query log to papertrail
* Emit a watchdog when the country_count page is being updated.
* Check that all tables are innodb
* Turned on `catch_workers_output = yes` in fpm config so we can see when they emit issues.

**Comment by rfay** [comment]
This [morning's failure](https://papertrailapp.com/systems/warmshowers/events?q=fpm&r=542766010588246022-542778694486503430&t=1433344863&ut=9%3A21%3A03) showed the meltdown occurring right after a deadlock inserting into the cache. This is a longstanding problem but never thought it caused any actual difficulty. I even used to have a patch in there to work around it.

```
Jun 03 09:21:03 warmshowers php-fpm:  [WARNING] [pool www] child 32093 said into stderr: "NOTICE: PHP message: PHP Warning:  Deadlock found when trying to get lock; try restarting transaction"
Jun 03 09:21:03 warmshowers php-fpm:  [WARNING] [pool www] child 32093 said into stderr: "query: UPDATE cache SET data = &#039;a:1690:{s:18:\&quot;admin_menu_display\&quot;;s:1:\&quot;0\&quot;;s:21:\&quot;admin_menu_margin_top\&quot;;i:1;s:25:\&quot;admin_menu_position_fixed\&quot;;i:0;s:19:\&quot;admin_menu_show_all\&quot;;i:0;s:24:\&quot;admin_menu_tweak_modules\&quot;;i:0;s:21:\&quot;admin_menu_tweak_tabs\&quot;;i:0;s:11:\&quot;admin_theme\&quot;;s:1:\&quot;0\&quot;;s:29:\&quot;advanced_forum_add_local_task\&quot;;i:1;s:37:\&quot;advanced_forum_collapsible_containers\&quot;;s:6:\&quot;toggle\&quot;;s:37:\&quot;advanced_forum_default_collapsed_list\&quot;;a:0:
```

**Comment by rfay** [comment]
This [afternoon's failure](https://papertrailapp.com/systems/warmshowers/events?q=fpm&r=542855579279077386-542859693358624782&t=1433364960&ut=14%3A56) showed the same avalanche, but no sign of the deadlock being involved.

**Comment by rfay** [comment]
After a couple of days with no incidents, [this morning's](https://papertrailapp.com/groups/1355264/events?q=fpm&r=543830040224509956-543857406644629504&t=1433601191&ut=8%3A33%3A11) caught us by surprise. 

Next steps:
- [ ] Switch to static pool, as dynamic isn't even needed for our situation
- [ ] Switch to the default config file or something near it?

It seems that this must have been caused by an upgrade to php at some point, and perhaps our config is bringing to the surface some bug that wouldn't be seen with default config?

**Comment by rfay** [comment]
Upgraded all packages, dist-upgrade to mariadb 5.6; also installed a new grub. Crossing my fingers that it will reboot ok.

**Comment by rfay** [comment]
When [today's episode happened](https://papertrailapp.com/groups/1355264/events?r=544632156077731840-544633055592361996&t=1433787706&ut=12%3A21%3A46) I tried an strace on the master process and saw it only polling the children.

**Comment by kalpaitch** [comment]
Another incident 10 minutes ago. Restarted php5-fpm. Log - https://papertrailapp.com/systems/warmshowers/events?r=544796664180027394-544800399602003970

**Comment by rfay** [comment]
Nice work, less than 2 minutes downtime. 

This was 3 SIGSEGV's in a row, that triggered a reload. I have changed the emergency_restart_threshhold to 10, since we have way more running than we need anyway. As you pointed out, the SEGV might have been from a mandrill incoming.

**Comment by rfay** [comment]
Added mysql-slow.log to logging, so we should see the context if anything in there is related.

**Comment by rfay** [comment]
Good news: We've been 2 days without a crash, but it's the middle of the week and weekend has highest usage.

The failure that @kalpaitch restarted for was a one-off, I don't think related to the main issue. We had an email in the inbound queue which mandrill sent to us periodically, and it caused a SIGSEGV that killed php-fpm handler. 3 of those (due to a setting) caused a restart of the whole php5-fpm family. In that case the restart failed. That problem finally stopped happening when I blacklisted that sender and tossed the incoming event.

So the bottom line is that we're a few days into the static pool config without the normal problems. However, the max_active_processes did get up to 46 at some point, which seems odd since we're normally in the 14-20 range. (We run 75 processes in static pool right now, which is quite a lot for the level of traffic we have.)

There are a number of suspicious things:

1. Why are SIGTERM timeouts happening every 10 or 15 minutes? `Jun 11 09:22:42 warmshowers php-fpm:  [WARNING] fpm_children_bury(), line 252: [pool www] child 14226 exited on signal 15 (SIGTERM) after 7189.199345 seconds from start`. We currently have `php.ini:max_execution_time = 30` and `request_terminate_timeout = 600` in pool.d/www.conf. I believe the SIGTERM is a result of the 600 (10 minutes!) being exceeded. This would fit with the oddity of seeing stack traces when we had the slow log going. 
2. [Some internet sources](https://groups.drupal.org/node/229898) are skeptical of     `fastcgi_keep_conn on; # keep alive to the FCGI upstream` in the site config we use in the warmshowers pool config.

**Comment by rfay** [comment]
Turned off fastcgi_keep_conn

**Comment by rfay** [comment]
After turning off fastcgi_keep_conn, the number of active processes dropped to 1-3, and there has not been a single SIGTERM. Will keep monitoring.

**Comment by rfay** [comment]
No more SIGTERMs. Active processes most of the time at 1-3. Max was 20, before that was at 10.

Every 3 hours or so all 75 of the processes restart (after exiting with a 0). I imagine this is the result of the higher max active. They're all set to restart after handling 500 requests, and it seems that all are being treated equally, so they end up restarting around the same time.

Hoping this weekend goes well. If it does we'll:

- Trim the number of processes in the pool down to 40 or so
- Turn on the php slow log again to see what we see.

Overall, my take is that switching to static pool was the key win so far, then that turning off fastcgi_keep_conn made for much more appropriate use. 

I think I understand why the serialization warnings happen, see https://github.com/warmshowers/Warmshowers.org/issues/564#issuecomment-111301600, and IMO we should just ignore them right now.

Crossing fingers for the weekend.

**Comment by rfay** [comment]
No new recurrences of the base problem. I had to reboot the system just now for s server security patch, so we're starting over but fingers crossed.

**Comment by rfay** [comment]
Lowered pool size from 75 to 30, set max_requests up from 500 to 5000 (number of requests a child serves before gracefully dying and restarting).

**Comment by rfay** [comment]
Yay, I think we have beat this one, so will close it for now. IMO it turned out to be the inappropriate combination of fastcgi_keep_conn with a dynamic pool. We first switched to static pool and didn't see the (same) error after that. We then turned off fastcgi_keep_conn. I think either might have solved it. But now we have a pool of 30 and don't typically use 10% of that.
