### ISSUE TITLE
Improve minimum word limit on profile for new members

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#574]
It is possible to bypass the validation on the About Me field that requires at least 15 words by including HTML tags and other characters separated by a whitespace that would other wise be filtered out by the relevant Drupal plain text filters.

Edit: When we work this one to make the word count correct, let's make the min word count configurable, up it to 30 by default, and give prompting about what we're asking for if they fail the validation. 

Don't forget that adding this validation (if it increases the word count) will break perhaps thousands of members when they edit their account. And we don't want that. Perhaps the validation should just be on creation.

Also, the validation error, for new members, can suggest how they can improve the profile

**Comment by kalpaitch** [comment]
Well, it doesn't actually filter out all tags but if there's no actual text inside the tags then nothing shows up, so just putting <p> </p> lots of times gets through.

In fact it puts all tags unfiltered straight into the database, I also managed to get a js script tag into the database.

We should probably apply a filter to the About Me field before we count the words. But we should probably also apply a filter before we put such tags into the db @rfay?

**Comment by rfay** [comment]
We deliberately allow filtered html into the DB, and it's used on some nefarious profiles like https://www.warmshowers.org/users/randyfay

But super interesting that this could be the cause of empty profiles. Will be interesting to look at the next one. Unfortunately, the most recent one was deleted before I could look at it.

**Comment by simison** [comment]
Guys, be careful what html you allow there. You shouldn't only be looking for SQL injections but for XSS attacks, too.

At Trustroots we've got [pretty restricted set](https://github.com/Trustroots/trustroots/blob/master/modules/users/server/controllers/users/users.profile.server.controller.js#L60-L74) of allowed tags.

Check
https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet and https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

**Comment by rfay** [comment]
Drupal is quite good at this; we use filtered html, a very restricted set. Glad to have you watching!

**Comment by simison** [comment]
:+1:

**Comment by rfay** [comment]
So the Drupal philosophy is to accept anything from the user (and store that) but to sanitize on presentation. This is done quite carefully, but of course as pointed out is critical everywhere.

**Comment by rfay** [comment]
Speaking of which: Probably what's going on here is that evil stuff is being put in, and sanitized on output, which is why we have an empty user "about me". Hope to look at this in the db next time.

**Comment by kalpaitch** [comment]
http://xkcd.com/327/ :)

**Comment by rfay** [comment]
I remember that one! It's the most famous xkcd of all time :) It must be
used for every security presentation in history :)

**Comment by rfay** [comment]
I edited the OP to increase the word could when this gets worked.

**Comment by kalpaitch** [comment]
We have a new scenario whereby a user was able to create an account with just the following string in their About Me section: 'I ❤️'

To all purposes this fails the validation we have in place on the site. I can see just a few possible reasons for this: a) there was more entered in the box originally but it was stripped out (perhaps sql injection) after it passed our custom validation b) it was submitted not through drupal, perhaps through the app where there is different validatio (or none).

**Comment by rfay** [comment]
I'm thinking we are using a non-utf safe trim technique, so stuff gets truncated. This would be correlated with the increasing use of utf-8 emoticons in many editors. And it's possibly what we see in the example provided. 

Drupal filters on output, so in the example, sql injection or js should have still been visibl  when viewing the edit form. 

I think the problem could be how we handle. The text after validation, not the validation technique.

**Comment by rfay** [comment]
I have confirmed now that I can insert an emoji in the "about me" and it will be truncated at that point. Also, the userdata gets truncated, causing other problems.

For example, this in the userdata will result in truncation before the emoji:

This is a test, where I want to include ñnña información about myself.
An emoji: 

🎓
GRADUATION CAP
Unicode: U+1F393 (U+D83C U+DF93), UTF-8: F0 9F 8E 93
That should have worked, but it will be truncated

**Comment by rfay** [comment]
You can [fix mysql 5.5+ to handle 4-byte characters](https://mathiasbynens.be/notes/mysql-utf8mb4)
But unfortunately [Drupal doesn't seem to play well anyway](https://www.drupal.org/node/2488180)
How to strip 4-byte utf-8: http://stackoverflow.com/a/24672780/215713
