### ISSUE TITLE
Check all MENU_LOCAL_TASK items to make sure only appropriate paths are shown to users

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#600]
Make sure that no unecessary paths are shown in the MENU_LOCAL_TASK tab menu. This is particularly relevant to user/* paths on the profile pages.

At present the user/%user/orders path is showing up in the local tasks menu, it should be disabled as per the original functionality in hook_menu_alter() in warmshowers_site module.

**Comment by rfay** [comment]
I think you've got this now. Orders is fixed. Will deal with anything else as we come to it.
