### ISSUE TITLE
Theme: Check font sizing for consistency throughout site.

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#601]
Rationalization: Part of this task involves setting an appropriate base font size and ensuring this is overridden as little as possible and only when necessary.

Theme tweaks: The other part is ensuring all font sizes of the new theme match as closely as possible to the old theme within the bounds of the above base font size.

**Comment by rfay** [comment]
@kalpaitch, do you think this is still a live one, or should we close it and just deal with what we have?

**Comment by rfay** [comment]
Closing unless @jeanfrancoisbeaulieu wants to reopen it.
