### ISSUE TITLE
Theme: Rationalization of selector depth within all style sheets

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#602]
Some of the sass styles go into quite a lot of nesting, some up to half a dozen or more. We need to try and remove as much of this nesting as possible and reduce the selector depth where this doesn't alter their targeting.

**Comment by jeanfrancoisbeaulieu** [comment]
I'll try to work towards that. But 'ill need more knowledge about the site structure before I can start really cleaning it up.

**Comment by rfay** [comment]
Closing this unless @jeanfrancoisbeaulieu wants to reopen it.
