### ISSUE TITLE
Theme: Review font colours and links colours throughout the site.

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#604]
Rationalization: Part of this task involves defining all font colours used and reducing this to a consistent selection if necessary.

Theme tweaks: The other part is ensuring all fonts match with those on the old theme.

**Comment by jeanfrancoisbeaulieu** [comment]
I've started doing this. I want to clean up the css and create global text and links color and styles.

**Comment by rfay** [comment]
Calling this good enough. Anything more will get sorted out in redesign or along the way with @jeanfrancoisbeaulieu
