### ISSUE TITLE
Address all php errors and notices throughout the site.

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#612]
Must remove all errors and notices discovered during the d7 upgrade.

**Comment by rfay** [comment]
Amen

**Comment by kalpaitch** [comment]
Your meant to be on an airplane.

**Comment by rfay** [comment]
Let's make a separate issue for each one and kill them off quickly. I don't think that a meta-issue like this will help us. But we definitely want to fix each, even from contrib if possible.
