### ISSUE TITLE
Members who receive feedback from other guests aren't getting notified of this by email.

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#616]
Both Ken Francis and Lou Melini have informed me that when their last two guests left feedback for them they received no notification email.

Ken - https://www.warmshowers.org/users/mr-tour:
Lucas - https://www.warmshowers.org/user/92798 - left feedback for Ken on Jul 8, 2015. An email was sent to Lucas to notify him of this at 5:57 pm, but no email was sent to Ken. Checked.
Kerry - https://www.warmshowers.org/users/kiwicyclical - left feedback for Ken on Jun 27, 2015. An email was sent to Kerry to notify her of this at 4:45 am, but no email was sent to Ken. Checked.

**Comment by rfay** [comment]
Please say why you closed it. There have been complaints about this in the
forums also.

**Comment by kalpaitch** [comment]
Oh yes it is closed because I linked it to the other issue 621 which is to review all email notifications and make sure they're getting sent. It also ties in with the review of triggers and actions ticket.

**Comment by rfay** [comment]
Ok cool thanks. I just read the email notifications and don't click through
so probably missed one.  Current intended setup of feedback notifications
is to notify only on positive feedback. It was changed from all feedback a
few months ago to calm down tit for tat negative feedback. It's done by
rules and is thus untranslatable, which is another open bug.
