### ISSUE TITLE
Upgrade prod server to use settings.local.php and include non-sensitive settings.php in git

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#618]
Would like to consider upgrading the prod server to use a settings.local.php file and include the main settings.php (stripped of all sensitive data and settings) in git.

Our d6 dev environemnts are already using settings.local.php and it would make testing the process and rolling back just a little bit more simple.

**Comment by rfay** [comment]
Ok to do. With care.
