### ISSUE TITLE
Feedback email notification verification

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#621]
Edited by rfay: On the D6 site, the rules-based email that notifies members of feedback given to them is broken, see token problem debugged below by @kalpaitch. We need to verify that it's working on D7.

There have been mumblings that email notifications are not getting through to users when someone leaves feedback for them - https://www.warmshowers.org/node/107084#comment-16183. I don't know whether this is something that was working and has stopped or something that is erratically not working.

But we need a review of all notifications sent by the site so that we can test them all correctly once upgrade.

@vortle86 It would be good to make sure there is a test case for each of the notifications we find.

**Comment by kalpaitch** [comment]
Actually to be fair this ticket should really be included in https://github.com/warmshowers/Warmshowers.org/issues/535 even though one is reviewing and the other testing.

**Comment by kalpaitch** [comment]
WTF, I'm opening about five tickets for the same thing. Closed a duplicate ticket because this one is more detailed - https://github.com/warmshowers/Warmshowers.org/issues/616

**Comment by kalpaitch** [comment]
I don't know what changed here but the token used to detect who to send the feedback to is [node:field_member_i_trust-mail]

And the tokens available are:
[node:field_member_i_trust-link]
[node:field_member_i_trust-name]
[node:field_member_i_trust-path]
[node:field_member_i_trust-uid]
[node:field_member_i_trust-url]

Spot the difference??? What happened to our email token, it was apparently working once upon a time...

**Comment by rfay** [comment]
Emails are all being sent to uid@warmshowers.org, which is pretty strange.

![outbound_activity___mandrill](https://cloud.githubusercontent.com/assets/112444/9582007/0977b99c-4fc0-11e5-9df8-9a714bfe6b13.png)

**Comment by rfay** [comment]
I think this is worth solving in the short term and making sure that it's not broken in D7

**Comment by rfay** [comment]
So what happened was that we were using CCK 6.x-2.9 from 2011, but it was a *patched* version. At some point in the misty past we had patched 6.x-2.9, not put the patch anywhere (apparently?) but moved cck into the patched directory. 

On June 17, 2015, the CCK 6.x-2.10 security release came out and I didn't even look to see that it was in the patched directory, but just used drush to upgrade it. ([commit](809f63b3f0e67583013727625338148c9a66d4d9). 

Here's the patch:

```
diff -r ./includes/content.token.inc /Users/rfay/workspace/warmshowers/docroot/sites/all/modules/patched/cck/includes/content.token.inc
168a169
>       $tokens['user reference']['mail'] = t('Referenced user email address');
183a185,187
>       $user = user_load(array('uid' => $item['uid']));
>       $tokens['mail'] = $user ? $user->mail : '';
>
```

**Comment by rfay** [comment]
@kalpaitch AFAICT there has been no rule introduced into D7 for this. It looks to me like ws_rules_features has just 2 things in it at admin/structure/features:

* Admin notification of new account creation
* Redirect to profile page on submit on account

So I'm kicking this one mostly back to #534 for rules implementation for D7

**Comment by kalpaitch** [comment]
The tokens are correct by default in D7, no need to issue a fix there.
