### ISSUE TITLE
Add responsiveness metric to rest api

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#634]
Return responsiveness metric (x and y in: "x responses to y requests over the past year") in response to GET /services/rest/user/<UID>.

This seems pretty important for the mobile apps.

**Comment by kalpaitch** [comment]
@klzig Please read this issue - https://github.com/warmshowers/Warmshowers.org/issues/406

There are two big issues to sort out upstream before we can approach this. #mytwocents

**Comment by rfay** [comment]
#406 will fix this, and completely agreed that it's crucial. Closing.
