### ISSUE TITLE
Tabs on user profile should be sized and placed correctly

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#663]
The tabs on the user profile still need some work to make them the right size.

![nancy_lewis_and_randy_fay___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/9479220/a5a10e6c-4b39-11e5-8bd6-76b9476d3f8a.png)

**Comment by kalpaitch** [comment]
updated in PR https://github.com/warmshowers/Warmshowers.org/pull/667

**Comment by rfay** [comment]
After #667 it still looks like this; I did do compass watch after pulling (finally) and cleared cache:

![randyfay___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/9480884/09c3a5cc-4b43-11e5-8743-037fae8434b0.png)

**Comment by rfay** [comment]
More detail - Would love to have it respect that content area above the tabs, since it's variable. This screenshot is taken with latest 20150921_css_fontsizes, @jeanfrancoisbeaulieu 

![nancy_lewis_and_randy_fay___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/10032858/08432ec8-6143-11e5-93a7-0e582a1856df.png)
