### ISSUE TITLE
Remove some tabs from user profile

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#665]
The orders tab shouldn't be on the user profile, or if it is it should be renamed. We're providing access to this with a special block. We should probably fix the menu alter to adjust this.

![feedback___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/9479631/5e0933de-4b3b-11e5-8f9e-a9b979c7f433.png)

**Comment by kalpaitch** [comment]
Yea, that is what I had intended with ticket https://github.com/warmshowers/Warmshowers.org/issues/600. I guess they are pretty much both the same thing.

I had one thought which would be to add a view on the same path as that menu item and just force it to request higher permissions. That way admin can still see a user's order... and saves baking in any custom menu alterations.

**Comment by rfay** [comment]
Closing in favor of #600 then - thanks. I think this was done with hook_menu_alter in d6.
