### ISSUE TITLE
D7 Forum theming and configuration

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#666]
This includes:

- [x] Enabling advanced forum
- [x] Making sure the user picture has the correct style (it's currently using the profile_picture size, which is imagecache_profile's default, although it's configured configured to be thumbnail)
- [x] Making the below-comment links be properly styled (linkbutton mostly)
- [x] Overall theming. 
- [x] Is adv forum actually providing the "tabs" on forum posts?
- [x] Posting-User picture for both main post and comments should probably be left of username.
- [x] Nice CSS frame on user-picture would be good (below) as on production

See [@vortle86 test results](https://www.evernote.com/shard/s246/sh/027b0fa7-fec1-48e9-a278-913ae082f26d/77df593a19b2b911), so many problems, even beyond it being ugly.

Picture styling on live production has a nice frame around it:

![include_more_hospex_databases_for_the_warmshowers_app___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/10257497/076afa06-6915-11e5-9bd1-6cbf6ba28b46.png)

**Comment by jeanfrancoisbeaulieu** [comment]
Mostly done on the styling side.
There is still the question of tabs not always appearing and maybe mechanics I haven't tests.

**Comment by rfay** [comment]
There are a couple of checkboxes not accounted for in the OP

**Comment by jeanfrancoisbeaulieu** [comment]
this should be all fixed now

**Comment by rfay** [comment]
Awesome!
