### ISSUE TITLE
Get messages API response has changed in D7

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#698]
Testing the Windows Phone 7 app on the staging server / I discovered the response to /services/rest/message/get has a different structure that breaks the app.

"participants":[{"uid":"41682","name":klzig_test"}]}}

has changed to

"participants":{"user_41682":{"uid":"41682","name":"klzig_test","pass":"U$S$92aIFWqbHFIA9r4cKgtjXpyBwWg2W6s9HQu/E8t1e6Wbu005UDWO","mail":"user_41682@localhost... <and a whole bunch of redundant user info that didn't used to come back> ...}}

The .net json serializer available to WP7 actually can't parse the new format.  And the additional account information is unnecessary.

Old complete response with a single participant:
[{"thread_id":"34632","subject":"test from klzig_test","last_updated":"1357758921","is_new":"1","participants":[{"uid":"41682","name":"klzig_test"}]}]

New (D7) complete response with a single participant:
 [{"thread_id":"674835","subject":"Thank you","last_updated":"1410105011","has_tokens":"0","is_new":"0","count":"8","participants":{"user_4252":{"uid":"4252","name":"testuser","pass":"U$S$92aIFWqbHFIA9r4cKgtjXpyBwWg2W6s9HQu/E8t1e6Wbu005UDWO","mail":"user_4252@localhost","theme":"","signature":"","signature_format":"1","created":"1164772843","access":"1433471263","login":"1433471263","status":"1","timezone":"America/Los_Angeles","language":"en-working","picture":{"fid":"107390","uid":"4252","filename":"picture-4252.jpg","uri":"public://pictures/picture-4252.jpg","filemime":"image/jpeg","filesize":"118705","status":"1","timestamp":"1434046303"},"init":"user_4252@localhost","data":{"fullname":"Test User","notcurrentlyavailable":0,"fax_number":"","mobilephone":"555 555-5555","homephone":"","workphone":"","nearest_large_city":"San Francisco","preferred_notice":"7 days","cost":"","maxcyclists":"2","motel":"4 blocks","campground":"5 miles","bikeshop":"4 blocks","languagesspoken":"English","URL":"","comments":"I am an avid cyclist..","services_available":"0","howdidyouhear":"","roles":["2"],"htmlarea_isenabled":"1","picture_delete":0,"picture_upload":"","bed":1,"food":1,"laundry":0,"lawnspace":1,"sag":0,"shower":1,"storage":0,"kitchenuse":1,"form_build_id":"form-c0sG6RHuGVW81IHgfPVXHBrOvmFA9KDCzACm9jhntpE","becomeavailable":1410246000,"set_unavailable_timestamp":"","set_available_timestamp":"","last_unavailability_pester":"","pending_force_password_change":"0","geoip_location":{"country":"United States","country_code":"US","city":"Atascadero","zip":"93422","region_code":"CA","region":"California","latitude":35.4894,"longitude":-xxx.xxxx,"time_zone":"","ip_address":"xxx.xxx.xxx.xxx","timestamp":1433457972},"uc_stripe_customer_id":"cus_66rM3vgHJTVDRW"},"roles":{"2":"authenticated user","15":"comment posting user","19":"donation-basic"},"fullname":"Test User","notcurrentlyavailable":"0","notcurrentlyavailable_reason":null,"fax_number":"","mobilephone":"555 555-5555","workphone":"","homephone":"","preferred_notice":"7 days","cost":"","maxcyclists":"2","storage":"0","motel":"4 blocks","campground":"5 miles","bikeshop":"4 blocks","comments":"I am an avid cyclist...","shower":"1","kitchenuse":"1","lawnspace":"1","sag":"0","bed":"1","laundry":"0","food":"1","howdidyouhear":"","languagesspoken":"English","URL":"","becomeavailable":"1410246000","set_unavailable_timestamp":"0","set_available_timestamp":"0","last_unavailability_pester":"0","hide_donation_status":null,"email_opt_out":"0","oid":"4252","type":"user","street":"","additional":"","city":"San Luis Obispo ","province":"ca","postal_code":"93401","country":"us","latitude":"xx.xxxxx","longitude":"-xxx.xxxxx","source":"1","comment_notify_settings":{"uid":"4252","node_notify":"1","comment_notify":"1"},"recipient":"4252"}]}]

**Comment by rfay** [comment]
Please, please don't disclose the address of the staging server @klzig - I've edited your comment.

Your posting also shows that the password hash is being exposed to the API, which just won't do.

**Comment by rfay** [comment]
I'd appreciate it if you could see if you can figure out why your json parser can't handle this. It's hard to justify backwards compatibility work on something that is being used by so few people, as you can imagine.

**Comment by klzig** [comment]
Yeah, should have sent you that json via private message.

I struggled with the new POST /services/rest/hosts/by_keyword response and discovered that the .net DataContractJsonSerializer I'm using simply can't handle the latter structure.  Then I encountered the problem on the messages call which is a bigger deal because the app is already using it.  Call it a bug or a feature, but it seems to be a well-known fact for people unfortunate enough to have gone down this road.  I've seen the argument made that the former is valid json and the latter is not, because javascript doesn't have a native dictionary object.  That seems kind of silly to me given every other parser I know of handles it, apparently including microsoft's deprecated javascript serializer.  Not sure what you mean about Postman, all I've used it for is to bring back a blob of json, which is before the problem starts.

So the obvious choice is to move to a decent deserializer-- json.NET seems like the hands-down choice, but they don't appear to support WP7 anymore.  My plan is to switch to this when I move to WP8 but that has a number of other work items that will likely push it out past the point D7 goes live.

Since I didn't expect this call to change for D7, my plan was to quickly upgrade the WP7 app and then replace it with a WP8 version in the fall/winter timeframe.  It's possible no one is running the app on WP7 at this point but it would be nice to get a compatible version in the store before I move on to WP8.

Question:  is this API change intentional and necessary moving forward or was it just an unintended side-effect of the upgrade that can be fixed?  Seeing all of the unnecessary and redundant data coming back made me think it was the latter.  If the former I'd be curious to know the reasons for the change.  I'm not sure of the value in bringing back all the user data for every participant in a thread. If it is important it could probably be accomplished with a list of user objects that matches the first format.

Some options are:
* Move back to the list-form of the json and release the WP7 app per my original plan
* Pull the WP7 message functionality (but that's pretty deeply integrated in the app)
* Skip WP7 and move to WP8 (that will likely leave a gap where the app is broken)
* Switch to a temporary parser for WP7 or write my own (waste of time)
* I'll look more into running json.NET for WP7, seems like that should be possible. But I'd still like to understand why the call changed in the first place.

If the answer is that the breaking change to the API is staying and there will be a hard cutover to the new service, we'll need to coordinate closely to avoid the app temporarily breaking for people on tour.

Yet another possibility:  Follow common practice for breaking API changes and keep the deprecated call around for awhile.  I will probably be able to pull the WP7 app from the store once the WP8 version is out, at which point the deprecated call could be pulled.

**Comment by rfay** [comment]
Thanks for trying to find a way to parse it Kurt.  I assume that other parsers, like Postman for example, have no trouble - there's no problem with the format of the JSON is there?

The change here is driven by the upgrade to Drupal 7, which which required a whole different module to provide the privatemsg service.

**Comment by klzig** [comment]
It looks like I'll be able to use json.net to handle the new format.  I don't think the new format is optimal but it's not structurally wrong.  Irrespective of the format change that caught me, it would be an improvement if there was a way to turn off sending back all the user details for the participants collection.  All that's absolutely needed is uid and name, fullname would be a useful addition.

**Comment by rfay** [comment]
I definitely agree that the participants section is bad, and will remove most of that in order to solve the security issue. I'll try to make it look mostly like the D6 version.

The privatemsg module in D7 didn't provide any capability for messages, but one person had put together an experimental version. It wasn't perfect. That's where this came from. Now that I understand your issue I fully agree with it.

**Comment by klzig** [comment]
Working great now, thanks.
