### ISSUE TITLE
Messages disappeared

### ISSUE THREAD

**Issue by nicolas-raoul** [warmshowers/Warmshowers.org#699]
![ws](https://cloud.githubusercontent.com/assets/99590/9567173/655ac290-4f5c-11e5-8abb-f2ee13bed450.png)

Also confirmed by my guests and by several persons on the forum at https://www.warmshowers.org/node/38#comment-16585

**Comment by rfay** [comment]
This is a server issue, working on it with OVH. Appreciate you reporting it! The contact form on Warmshowers.org is probably better for immediate support of an issue like this. Thanks!
