### ISSUE TITLE
Need new image size for WP app (456w)

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#700]
D7 removes the reference to the location of the original host image.  The windows phone app relies on this and needs an alternative.  One of the two new file sizes would work but is not optimal for the WP design.  It would be great if a third rendering from imagecache could be provided that scales the original to a width of 456 and doesn't specify a height (maintains original aspect ratio) and doesn't crop.  

Some windows phones use a different screen resolution, but they maintain the same aspect ratio and the image container will automatically scale the picture to fit.  So one WP-specific size is sufficient.

Thanks

**Comment by rfay** [comment]
So we'll just narrow to 456x 

Note that in some cases this will be upsized, but that's true of the others as well.

@klzig do you think you'll have your app version done and out there before D7 deployment (meaning that we have to do this on existing D6 as well) or can we just do it in D7? Target D7 deployment is still early October.

**Comment by klzig** [comment]
If we come up with a quick solution to #698 I'll have it ready well before the upgrade goes live, but I have no problem delaying publication until then. I could also code for either. Either way I don't think we need to worry about D6 for this.  

And yes, I'd expect some images to scale up to 456x, that's not a problem.  Thanks.

**Comment by rfay** [comment]
Created the mobile_photo_456 preset. Now will add it to the production site, make it available in the user service, make it available in D7 code, and migrate to D7 staging. It will be a bit before it's available.

**Comment by klzig** [comment]
Works great in WP app, thanks for getting this in.
