### ISSUE TITLE
Authenticated user footer cleanup

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#720]
There's a bit of work to be done on the auth user footer.

Note that "Password recovery" is now actually able to be used by auth user in D7. The problem is that an authenticated user has to *log out* to make use of the link. I think we should remove the "Password recovery" from the auth user footer menu.

**Comment by rfay** [comment]
Note that the "Mobile apps repeating a number of times" is a characteristic of the live D6 site, it's not an artifact of upgrade. And it seems to be just the English version of the footer menu.

**Comment by jeanfrancoisbeaulieu** [comment]
I've removed the repetition of 'Hospitality for Touring Bicyclists Worldwide' and subset of the menu by disabling the block in the footer in Drupal admin.

**Comment by rfay** [comment]
This one will be resolved by #813. May require a hook_update_N() but easy to solve there, so it's essentially a dup.
