### ISSUE TITLE
Message sub-tabs not formatted properly

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#745]
The message sub-tabs seem to get into the line with the main tabs.

![my_account___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/9726016/0bcf8c16-55aa-11e5-80ef-772c716b028c.png)

**Comment by kalpaitch** [comment]
![screenshot from 2015-09-09 20 37 59](https://cloud.githubusercontent.com/assets/334114/9772234/bed98ee0-5732-11e5-8825-3d84df3c2acb.png)

@rfay Are you happy with this? Happy for suggestions or for you to close.

**Comment by rfay** [comment]
Yes, it looks great to me, thanks. Commented on how good it looks over in #752.
