### ISSUE TITLE
Profile URL /users/username doesn't work for everyone

### ISSUE THREAD

**Issue by simison** [warmshowers/Warmshowers.org#769]
I stumbled upon an issue with WS profile URLs when I started linking to WS profiles from Trustroots.

Both of these work most of the time:
/users/username
/user/123123

...but for some users only the numeric user id version works, although they have the username set. 

That profile is ~1.5 years old. I can probably send you an example profile via email if you need.

**Comment by rfay** [comment]
No, I turned off that URL alias feature a long time ago (for new users). Also, it never did work predictably with users/username because many usernames urlencode differently, etc.

The only correct way to get to a user URL is with user/UID where UID is the numeric UID.

**Comment by simison** [comment]
Aight! Great to know. :-) Should've checked up with you before.

BTW Heads up, this would've been much better solution from our side: #716
