### ISSUE TITLE
Self-cancellation configuration and test

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#775]
- [x] Configure the user cancellation confirmation email
- [x] Remove the confirmation email step, because it would require them to log in (#779) - See [stackexchange](http://drupal.stackexchange.com/a/32427/449)
- [ ] Specify new items for translators
- [x] Links like user/UID/delete become user/UID/cancel (See admin emails especially). Consider adding a URL alias, consider leaving the name of the button "Delete account"
- [x] Verify admin workflow - should be no confirmation email required for spammers, but yes for requests by members?
- [x] Review user workflow per #779 - Should we even do the email confirmation thing?

**Comment by kalpaitch** [comment]
Really need to update functional tests for this. As with the private_mesage attachments, I think anything that introduces a departure from our existing practices/work flow needs to find its way into a change log, probably should have been monitoring this more closely. And then that can help us update tests and share with help desk support @rfay

**Comment by rfay** [comment]
Outstanding points, all. I added #842 for user cancel workflow.

I have been tracking helpdesk issues in #776 - please take a look and see if you know of anything else new there.

Translator issues are in #581, and we're getting together a mailing list for them. There will be quite a lot of new things to learn. Field translation is the biggest issue I've had so far.
