### ISSUE TITLE
D7 admin/helpdesk training tasks (and permissions)

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#776]
- [x] New cancellation procedures (requiring user click link). The link is user/UID/cancel now.
- [x] iOS app versioned before 5.0 are completely broken, they didn't make the deadline. Android before 1.5.0 also
- [x] Flood resolution (if somebody tries too many times to log in, etc. (admin/config/system/flood-unblock)
- [x] Spammer deletion is now *blocking* rather than actual deletion
- [x] Any attachments to existing pre-upgrade private messages will not come over on the upgraded site, there was no upgrade path for them. (#833)

**Comment by kalpaitch** [comment]
Ah cool. Hadn't seen this.

**Comment by rfay** [comment]
I think all of these are taken care of.
