### ISSUE TITLE
Read feedback API response has changed in D7

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#787]
The json response to GET /user/<uid>/json_recommendations has changed.  

This is easy enough to snap to on my end, just want to make sure this is stable first.  The only problem I see with the new timestamp format (formatted string instead of integer epoch) is that it may be inconsistent with other timestamps returned by the API.

Old: 
"field_hosting_date_value":1309413600
"field_guest_or_host_value":"Host"
"field_rating_value":"Positive"

New: 
"field_hosting_date":"2014-07-00T00:00:00"
"field_guest_or_host":"Host"
"field_rating":"Positive"

**Comment by rfay** [comment]
Not sure what happened there, it's supposed to be a unix time int. I'll try to get it sorted out if I can at all.

**Comment by rfay** [comment]
It was actually not just that, but also that "field_hosting_XXX_value" changed to "field_hosting_XXX". I'm attempting to provide both. 

Interestingly a lot of effort had gone into this, and it was (I claim) working in late may :)
