### ISSUE TITLE
active-trail handling for main menu

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#803]
The active-trail is not properly generated in some menus. It works on FAQ and Forum, but not on `<front>` or "My Profile".

Probably https://www.drupal.org/node/1578832

Issue can be worked around with menu_block, or with custom theming, apparently. https://www.drupal.org/node/1571058

**Comment by jeanfrancoisbeaulieu** [comment]
Doesn't work for me for 'My Profile'

**Comment by rfay** [comment]
You have to flush the cache (specifically the theme registry) for this to start working, because it introduces a new theme element.

You can do that either in the admin menu, left side, flush cache, or with `drush cc all`or `drush cc `theme-registry`. 

Or for completeness, use the deploy script in /shell, which does all the things that need to be done with new code.

**Comment by jeanfrancoisbeaulieu** [comment]
That works, thanks!
