### ISSUE TITLE
Remove block placement via fe_block module

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#813]
Contrary to expectations, our context block placement is *not* overriding block-module-based block placement. I guess we have to 1) remove from block settings and put in features or 2) do a hook_update_N() or 3) use [Context Block Disable](https://www.drupal.org/project/context_block_disable) to solve this problem. 

Blocks known to be a problem:
- [x] Auth footer 2nd "hospitality for touring cyclists worldwide" (only thing left in footer menu) (admin/structure/block/manage/block/18/configure)
- [x] Site mission (admin/structure/block/manage/block/17/configure)
- [x] Drupal-provided user-registration (admin/structure/block/manage/block/16/configure)

**Comment by kalpaitch** [comment]
@rfay I'm in favour of doing a complete wipe in a hook_N_update and then a feature revert on all contexts. All those in favour say Aye! Also in favour of removing fe_block, all those in favour say Aye, Aye!

**Comment by rfay** [comment]
fe_block is the only way I know to use a feature to get rid of the title display on the block, so that's what it's currently used for.

A complete wipe of region settings (using block module) for all blocks in hook_update_N() is fine.

**Comment by rfay** [comment]
I found that there were remnants of the D5 module "blockcache" in the block table (and in the system table). I deleted those rows on production in both tables. I don't know yet whether that mattered.
