### ISSUE TITLE
Donation renewal email notifications

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#832]
We need to properly notify people:

- [ ] ~~When their automatic renewal charge is coming due~~
- [x] When their annual subscription is about to end and we'd like them to donate again (but this must be kept separate from the automatic charge notification)
- [x] When their annual subscription has ended and we'd like them to donate again
- [x] When their automatic renewal fails
- [x] When their automatic renewal succeeds/Whenever a new donation is made

**Comment by kalpaitch** [comment]
Full translation required.

**Comment by kalpaitch** [comment]
Message wording - https://docs.google.com/document/d/1HmKbgKcm5f2npoPCaKcVKdibovB0akX4GWuwDgSnATI/edit#

**Comment by kalpaitch** [comment]
Spanish messages - https://drive.google.com/drive/u/0/folders/0B7BR9Lnaifg6fjJqQ05LTDVBdE4tT3dXMUp0YjJjSjduZmxwdEZwaDM2MU1vUDhuSmR4VE0

**Comment by kalpaitch** [comment]
Still requires more translation.
