### ISSUE TITLE
Existing PM attachments are not migrating successfully

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#833]
There is no migration path for existing privatemsg attachments, see [issue](https://www.drupal.org/node/342733). 

If we want to have one... we'll probably have to dive into that issue.

I think we should leave it alone and let the existing attachments die. Private messages have a short lifespan anyway.

**Comment by kalpaitch** [comment]
I agree, as long as we make changes widely known to the help desk folks I don't see an issue. That's another story.
