### ISSUE TITLE
Make links a bit more obvious

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#835]
Hi @jeanfrancoisbeaulieu - I note that links are not as obvious as I think people expect them to be. They're obvious if you hover, but you have to be smart enough to hover to find them. Could we get them a bit more prominent? (BTW, they show a bit better in the screenshot than they do on my screen.)

![home___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/10229944/e82297b8-6837-11e5-9af2-fbaa1621d523.png)

**Comment by jeanfrancoisbeaulieu** [comment]
Yeah. I've made the links green but without underline, in a goal to make the site cleaner. Visited green are of a darker green for now.
I don't mind putting the underlines back on if you want.

**Comment by rfay** [comment]
Doesn't have to be underlined, just a little more obvious. There may be
people other than me who can barely see the difference.

Thanks!

**Comment by kalpaitch** [comment]
Looks good like you've done it now @jeanfrancoisbeaulieu. @rfay I reckon this should be closed??

**Comment by rfay** [comment]
@kalpaitch you're one of the people who can see the difference :) I think the update is still coming. Thanks.

**Comment by jeanfrancoisbeaulieu** [comment]
For links, I think color and/or underline are the only two option the be considered. I'll put the underline back.

**Comment by rfay** [comment]
It could just be a somewhat more differentiated color. Your call based on design and usability.

**Comment by jeanfrancoisbeaulieu** [comment]
fixed in [746653d110f893a0f2657e3cf4d715660925325e](https://github.com/warmshowers/Warmshowers.org/commit/746653d110f893a0f2657e3cf4d715660925325e)

**Comment by rfay** [comment]
Thanks!
