### ISSUE TITLE
Better messages popup goes at bottom of profile page

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#841]
On the profile page (only) the better message popup ends up on the bottom right of the viewport, with much of it unreadable. (On Chrome, MacOS)

To demonstrate, go to http://wsupg.dev/user/25216 as a normal user. You'll get denied, log in as a normal user to see the result.

![mark_fay_and_lola_jacobsen_and_august_swanson___warmshowers_org_and_yuyu_kim___warmshowers_org](https://cloud.githubusercontent.com/assets/112444/10232974/fcfa8608-6848-11e5-9d94-69664cec36c9.png)

**Comment by jeanfrancoisbeaulieu** [comment]
I saw that happen a lot with the inspector opened. I'll checked how it's positioned.

**Comment by jeanfrancoisbeaulieu** [comment]
Can't reproduce anymore. It's positioned with javascript it seems with absolute positioning.
