### ISSUE TITLE
D7:  /services/rest/message/markThreadRead returns 404

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#850]
Tested with WP app and postman.  All other calls appear to work.

**Comment by rfay** [comment]
Weirdly, that's commented out, 
https://github.com/warmshowers/Warmshowers.org/blob/site_d7/docroot/sites/all/modules/dev/ws_privatemsg_services/ws_privatemsg_services.module#L140-L162

**Comment by klzig** [comment]
That is weird.  I'm pretty sure it worked at one point on the old site because the WP app uses it, and I tested it.  But it's possible I've just been failing gracefully all this time.

**Comment by rfay** [comment]
It looks to me like this remained unimplemented because the module providing services did not even have this feature, so there was no way to wrap it. 

Let me know how critical this feature is.

**Comment by rfay** [comment]
I'm not saying it didn't work on the old site. The module providing the privatemsg services did not get upgraded to D7, so the code providing services is new. And in many cases I had to wrap its behavior to provide backward compatibility. In this case, though, there was apparently nothing to wrap.

**Comment by klzig** [comment]
This is important because my UI flags messages that are new and sorts them first.  A cyclist on tour with just a phone won't be able to clear the flag so all messages will appear new, for the entire tour.

It would be nice to get this working eventually but it certainly isn't a showstopper for D7.

**Comment by klzig** [comment]
I confirmed this does work today on the old site.
