### ISSUE TITLE
Super-simple html page to serve during the D7 upgrade

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#861]
Could you put together the simplest of html pages to serve during the upgrade? It would be best for it to simply have some embedded styles and probably show the towel logo.

**Comment by simison** [comment]
Feel free to use our [maintenance page html](https://github.com/Trustroots/trustroots/blob/master/public/maintenance/index.html) :-)

**Comment by jeanfrancoisbeaulieu** [comment]
Thank you @simison, will definitely base on that. By the way, congrats on your site, looks really good. I'll sign up later to have a full look.

@randy is handling the 503, thanks for the reminder.

**Comment by simison** [comment]
@jeanfrancoisbeaulieu thanks! Feel free to use UI/UX ideas. I think a lot of it could be applied to WS's use cases.
