### ISSUE TITLE
Invalid jpeg images on site - lots of them.

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#869]
I'm seeing a fair number of gd processing errors, especially with the contest photo view, etc.  We've already been seeing a *few* of these on the prod D6 site, but it seems like there are a lot now.

`Warning: imagecreatefromjpeg(): 'public://contest_photo/24478/DSCF3169.JPG' is not a valid JPEG file in image_gd_load() (line 232 of /var/www/wsupg.net/docroot/modules/system/image.gd.inc).`

I suspect this will be fixed by upgrading to PHP 5.6. It's annoying just now though, because it's going to cause a bit of user difficulty.

**Comment by kalpaitch** [comment]
Randy the example I was lookg at was this:
```
Warning: imagecreatefromjpeg(): 'public://contest_photo/24478/DSCF3169.JPG' is not a valid JPEG file in image_gd_load() (line 232 of /var/www/wsupg.net/docroot/modules/system/image.gd.inc).
```
The problem is that when I actually view, or download and view this jpg it does actually seem to be corrupted. Adding to this thread:
![dscf3169](https://cloud.githubusercontent.com/assets/334114/10417560/d74affc2-7037-11e5-9998-4bdb24e92d0e.JPG)

**Comment by kalpaitch** [comment]
https://www.wsupg.net/files/contest_photo/54611/DSC02583.JPG

**Comment by kalpaitch** [comment]
There seem to be 15 out of 961 corrupted jpgs in the contest_photo section:

/files/contest_photo/56979/2012圣诞元旦%20335.JPG
/files/contest_photo/56979/2012圣诞元旦%20376.JPG
/files/contest_photo/56979/2012圣诞元旦%20396.JPG
/files/contest_photo/23931/Across%20America%20II%202012%20111.JPG
/files/contest_photo/23931/Across%20America%20II%202012%20130.JPG
/files/contest_photo/23931/Coast%20to%20Coast%20America%202010%20158.JPG
/files/contest_photo/23931/Coast%20to%20Coast%20America%202010%20227.JPG
/files/contest_photo/54611/DSC02583.JPG
/files/contest_photo/24478/DSC_0338.JPG
/files/contest_photo/24478/DSC_0361.JPG
/files/contest_photo/24478/DSCF3175%20Bicycle%20Geograkim.JPG
/files/contest_photo//2273/IMG_6233.JPG
/files/contest_photo/55793/IMG_6623.JPG
/files/contest_photo/14959/pics%20Geoffray%20(103).JPG
/files/contest_photo/56979/Teror2013%20047.JPG

**Comment by rfay** [comment]
Thanks so much for the effort on this, @kalpaitch  - much appreciated. I think we should probably write a script to find the bad ones, then figure out what refers to them and delete that. It's a bit of work though. I traced a couple of these to their node, but it would be easier programmatically. There are many more in feedback nodes and some user profiles as well.

No idea how they could be corrupted when having been seemingly quiescent for years.

**Comment by rfay** [comment]
@kalpaitch added [script](https://github.com/warmshowers/Warmshowers.org/blob/7154069b94e919b3cb29c26734551e0721aa4aa9/resources/check_images.php) that walks file_managed looking for un-loadable images. 

Amazingly, on my local at least, I see 1531 total jpegs that can't be processed out of the 57156 jpegs we have in the file_managed table.

[badfiles.txt](https://github.com/warmshowers/Warmshowers.org/files/12064/badfiles.txt)

**Comment by rfay** [comment]
Going to leave this alone for now, assuming it's a result of just having bad images. May have to be reopened in the future.

**Comment by rfay** [comment]
Reopening this. I'm not sure we need to do anything but the files/pictures directory, but think we need to do that. And those don't require a lot of chasing since the UID is in the filename.

**Comment by rfay** [comment]
Ran the fix_user_images.php on prod.

**Comment by rfay** [comment]
I think mostly what's left would be recommendation photos. Probably shouldn't be too hard to do this to them, except that they are on the *field*, but the file_usage info is about the node...

**Comment by rfay** [comment]
We're not seeing these now. There are certainly some out there, but I think I'll close this until they show up as annoying.
