### ISSUE TITLE
Many messages lost when incoming can't load message id

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#877]
Update: The problem in this issue is that

1. Occasionally mandrill will send us a larger batch. This may be the result of something on our end or their end, but there's no reason we can't handle a larger batch.
2. When this problem occurs, we successfully receive the batch, but when looping through it, it calls the hook in ws_pm_email_notify_mandrill_incoming_event(). 
3. When validating the (successfully parsed) message_id, ws_pm_email_notify_mandrill_incoming_event() gets an empty array from privatemsg_message_load(), even though the message_id is clearly there. (This only seems to be a problem with messages after the first one in the batch.)
4. The result is that an email gets sent to the configured receiver explaining the problem; it can be re-sent successfully.

Techniques for studying and/or resolving this include:

- [ ] Trying to recreate it by creating large batches for debugging on staging.
- [x] Trying to recreate it by adding code to capture large batches that fail so they can be replayed on staging.
- [x] Add instrumentation in privatemsg_message_load_multiple() to emit a watchdog message when a load fails, with info about the context, perhaps the stack trace so we know if this only happens here.
- [ ] Convert the handling of incoming messages in ws_pm_email_notify_mandrill_incoming_event() to a queueing behavior, where the message can be handled later, whether it succeeds or not.

--- 

It seems that most or all of the messages which were outstanding during the upgrade failed to load when the site came up. I have about 130 in my inbox.

However, testing of current messages seems to work OK.

What happens here is that one message blocks Mandrill inbound. It's the way they have it set up and they like it that way. If one message is failing, they defer all following. So when a failing message gets removed from the queue, all the other ones come in.

What happens then is that (all?) these messages fail to be processed on our end, with an email message to admin like 

MANDRILL FAILED TO HANDLE: Failed to load message id 1598670 - message does not exist,

If you look at the situation there in the code, you see that it actually tried and failed to load the message, which certainly exists. And when the messages are manually re-sent, they go through fine.

**Comment by rfay** [comment]
Jack and I went through and re-sent all of these, and got almost all to go through.

**Comment by rfay** [comment]
After fixing/releasing an email from #551, we got the same problem again, loads of backed up messages, none go through. This is painful. Will need some instrumentation improvement I guess.

**Comment by rfay** [comment]
Latest batch of these was about 7:06am today - the log may have helpful info

**Comment by rfay** [comment]
This is a serious problem because it requires a huge manual effort when we have a failure. But I haven't figured out a way to recreate it, or found a code path that causes the problem.

**Comment by kalpaitch** [comment]
@rfay just trying to put some information on this ticket so I can track back. Is this the beginning of the problem?

`Error: POST to https://www.warmshowers.org/services/rest/mandrill_events failed with 502: <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> `

**Comment by rfay** [comment]
This is the one that failed, blocking everything up. Those are easy, you
just download the textfile and curl script and work on it later.

The *problem* is that all the stuff backed up behind this fails when it
starts coming in.

So I downloaded the one with the 502 and will try to send it later and see
what the issue is, but it's the least of our problems.

Thanks!

**Comment by rfay** [comment]
@kalpaitch I updated the OP above with more info.

**Comment by rfay** [comment]
Had a situation tonight where a lone message came through saying "Failed to load... does not exist", unrelated to the big batch situation. Could be that I'm not thinking right about when this happens.

**Comment by rfay** [comment]
The cache bypass approach did not make a difference - 15 messages this morning, when several items queued.

**Comment by kalpaitch** [comment]
So over the weekend we had a failed incoming message. The reason seems to be different to anything previously mentioned which makes me think there might be more than one cause, but the result is a segfault with ws_pm_email_notify.module (line 231):

```
  // Replace from our message divider to the end of the message
  $text = preg_replace('/[\r\n ]*[> ]*------* .* -----*\+(.|[\r\n\t])*$/', '', $text);
```

Will now try adjusting ` pcre.recursion_limit` based on http://stackoverflow.com/questions/20750757/php-segmentation-fault-during-preg-replace

@rfay Based on what you found do you think this could be a separate issue? Are there likely to still be private message loading issues?

**Comment by kalpaitch** [comment]
I have now introduced the queue, which has caught some of the errors and I am able to now keep retrying these to see what is going on. You can see errors because they'll be piled up in https://www.warmshowers.org/admin/config/system/queue-ui/inspect/mandrill_incoming

When I try to manually process one of these queue items I'm getting a 502 Bad Gateway response. Below is the log for this:
```
2015/12/21 16:04:38 [error] 30521#0: *849636 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 90.202.122.119, server: *.warmshowers.org, request: "POST /admin/config/services/mandrill_incoming/queue HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.warmshowers.org", referrer: "https://www.warmshowers.org/admin/config/services/mandrill_incoming/queue"
```

**Comment by leventyalcin** [comment]
@kalpaitch If PHP works as fastcgi, Could you please send me over how looks these two 
```
fastcgi_buffers ?? ??;
fastcgi_buffer_size ??;
```

**Comment by leventyalcin** [comment]
If the settings are like 

```
fastcgi_buffers 8 8k; 
fastcgi_buffer_size 8k;
```

please change these for the particular URL 

```
location /admin/config/services/mandrill_incoming {
  fastcgi_buffers 4 256k; 
  fastcgi_buffer_size 128k;
  fastcgi_read_timeout 120s;
}
```

Or increase the values. This change won't be site-wide and will only for madrill requests, but aware of that mandrill requests can consume huge amount of memory.

**Comment by kalpaitch** [comment]
@leventyalcin Just this one
`fastcgi_buffers 256 4k;`

**Comment by leventyalcin** [comment]
Do buffer_size as well. It's for initializing the buffer

On Tuesday, December 22, 2015, kalpaitch <notifications@github.com> wrote:

> @leventyalcin <https://github.com/leventyalcin> Just this one
> fastcgi_buffers 256 4k;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/warmshowers/Warmshowers.org/issues/877#issuecomment-166713196>
> .
>


-- 
Levent YALCIN
DevOps
http://about.me/leventyalcin

**Comment by kalpaitch** [comment]
Nah, that's what it was for the whole site.

**Comment by kalpaitch** [comment]
Closing this because although there are the occasional failure, of which there might be a few causes, these no longer block up the incoming mail queue or cause messages to be lost.

**Comment by kalpaitch** [comment]
And another one...2016/01/02 15:38:56 [error] 28714#0: *2497242 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 2.217.151.240, server: *.warmshowers.org, request: "POST /admin/config/services/mandrill_incoming/queue HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.warmshowers.org", referrer: "https://www.warmshowers.org/admin/config/services/mandrill_incoming/queue"

**Comment by kalpaitch** [comment]
Changing `fastcgi_buffers` doesn't appear to have any effect.
