### ISSUE TITLE
Google Map doesn't load if there is a Better Message pop up when logging in.

### ISSUE THREAD

**Issue by jeanfrancoisbeaulieu** [warmshowers/Warmshowers.org#878]
js error :
"Uncaught TypeError: Cannot read property 'msie' of undefined" in better_messages.js line 104

Should have been patched before the upgrade. Suspecting Better Messages might not be using the correct version of js or jquery

**Comment by rfay** [comment]
It may be that we lost a patch of better_messages.

For now better_messages is disabled.

**Comment by rfay** [comment]
Deployed the fix
