### ISSUE TITLE
search indexing is failing

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#879]
Search indexing is failing, either via drush cron or drush search-index or whatever.

**Comment by kalpaitch** [comment]
@rfay as discussed I have now re-indexed the site. The error was due to 
```
if (!user_is_logged_in() && $build['#node']->type == 'trust_referral') {
    drupal_not_found();
    exit();
}
```
in warmshowers_site_node_view_alter()

We will need to re-factor this code and either put this check in an access hook or make sure all re-indexes and cron runs are run as user 1. Or whatever.

**Comment by rfay** [comment]
Thanks so much for the work on this! Great that the site is indexed. Followups on the PR.

**Comment by rfay** [comment]
No longer critical, as we can now index. But that code should be improved.

**Comment by rfay** [comment]
Followups in #926
