### ISSUE TITLE
Feedback views improvements - footer, main view truncation

### ISSUE THREAD

**Issue by jeanfrancoisbeaulieu** [warmshowers/Warmshowers.org#880]
There are some discovered problems with the member_feedback_views

- [x] Picture below, double footer
- [x] The size truncation has been lost on the profile member_feedback display (https://www.warmshowers.org/admin/structure/views/view/member_feedback) - It was supposed to have a size limit, ..., and a read more link, instead of what it currently has, which is the whole body linked.

![image](https://cloud.githubusercontent.com/assets/9020402/10473243/38d3df5a-71f7-11e5-9bfe-3e492d92df0e.png)

**Comment by rfay** [comment]
Fixed these, thanks.
