### ISSUE TITLE
Footer design issues with D7 upgrade

### ISSUE THREAD

**Issue by CyrilWendl** [warmshowers/Warmshowers.org#886]
In the new D7 upgraded version of warmshowers.org, the footer has quite a large bottom padding, which I think is larger than the one of the D6 version:

![bildschirmfoto 2015-10-14 um 15 38 44](https://cloud.githubusercontent.com/assets/2380893/10485406/3904f278-728a-11e5-88b8-f5d9d87b9f56.jpg)

I guess it would also be good by the way if we could progressively change to SVG-based icons, as low-res pixel-based logos look somewhat disgusting on high-resolution screens (e.g., on current MacBooks or iMacs) (should I create a separate issue for that?)

**Comment by jeanfrancoisbeaulieu** [comment]
The light blue bar under the dark blue rectangle will disappear, I 'fixed' that but it didn't make it into the upgrade. Will be after the more important bugs are fixed.

Being 'Retina ready' or 'high density screen ready' icon wise is for a big site redesign imo. SVG icons aren't always a solution, and loading files double the resolution for everyone is also a pain. Wouldn't consider it for now, except maybe the main logo and stuff.

**Comment by CyrilWendl** [comment]
Perfect. Thank you @jeanfrancoisbeaulieu
