### ISSUE TITLE
/services/rest/message/markThreadRead returns 500

### ISSUE THREAD

**Issue by klzig** [warmshowers/Warmshowers.org#902]
If I specify a thread of mine that I know exists (1540188 for example) I get the following error:

Status 500 Internal Server Error : An error occurred (23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'is_new' cannot be null
Time 186 ms

If I specify some random number (that surely doesn't exist) the call returns True.

**Comment by rfay** [comment]
I'm able to replicate this.

**Comment by rfay** [comment]
This fix is deployed, and tests OK for me. I must have tested with an invalid thread_id - only thing I can think of. Sorry.

**Comment by klzig** [comment]
No worries, working great now.
