### ISSUE TITLE
Cron setup and configuration

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#905]
Cron has yet to be set up because search indexing is failing, blocking it. 

- [x] Set up daily cron
- [x] Set up specific queues as needed (like vbo)

Blocked by #879

**Comment by rfay** [comment]
This is now set up and working.

**Comment by kalpaitch** [comment]
https://github.com/warmshowers/Warmshowers.org/pull/928

**Comment by kalpaitch** [comment]
Ultimate Cron is now enabled and cron is being hit every 5 minutes.

**Comment by rfay** [comment]
Still some trouble, not with ultimate cron, but apparently with the search index outputting lots of markup. Forwarded the email. This will be fixed with a better solution to access control, I think.
