### ISSUE TITLE
'Logged in as' mentionin the header is not translatable

### ISSUE THREAD

**Issue by jeanfrancoisbeaulieu** [warmshowers/Warmshowers.org#918]
![image](https://cloud.githubusercontent.com/assets/9020402/10560131/5ed5b572-74cf-11e5-8e81-eea6cdd1308e.png)

**Comment by kalpaitch** [comment]
Hi @jeanfrancoisbeaulieu, it should be translatable, but the string to replace is:
`Logged in as !name | !messages | !logout`

Please leave the `!name | !messages | !logout` bit

**Comment by kalpaitch** [comment]
Changed translations back to what they used to be for all languages.

**Comment by jeanfrancoisbeaulieu** [comment]
Thanks. My error. The 'Translate Text' tool couldn't find the string.
