### ISSUE TITLE
contact_form_help block needs to be translated

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#921]
The contact_form_help block, created by default in the upgrade, is in English only.

I suspect we'll have to do the same thing that was done for registration_help and create our own block and put it there.

We should experiment with i18n_block module though - might do the job.

**Comment by rfay** [comment]
@kalpaitch this one is probably more important short term, but I also assigned #917, thanks so much.

**Comment by kalpaitch** [comment]
@rfay what do you mean when you say the contact_form_help block is created by default. It looks like this has been created manually by someone. I don't think we should be creating content blocks for the exact reason that they're not very good in D7 and below. I think we should instead do what you've done with the registration_help block or we could create a node block??

**Comment by kalpaitch** [comment]
I've created a node block here - https://www.warmshowers.org/contact/help - and marked it for translation. Because we can't deploy with features any more and the context ui module is disabled or not available to admin users I can't deploy this. @rfay I don't know whether this is deliberately disabled so can I leave the deployment/configuration of context to you?

**Comment by rfay** [comment]
- So on D6, contact help was a translatable variable. In D7, the upgrade automatically turned that whole thing into a block. It would be just fine for it to be a nodeblock, which would make everything easy for everybody. We can copy the translations in as we have them on D6 verson.
- We *can* still use features, we just can't revert live ones that are changed (unless we take the time to re-save them back into features). Thanks for your patience with me on this. The dynamic nature of admin flows much better if things can change incrementally, especially at a time like this. I've been changing views and rules several times a day.
- Context UI is live and usable, not sure - do we have a privilege problem? (Edit: I found lots of privs that were missing from admin, and turned them on, so you'll find it there now.)

I'm ok with your nodeblock approach, but we should go ahead and gather the translations for them if possible. I can do that too.

**Comment by rfay** [comment]
You're fantastic, and this was exactly the right approach. 

I copied and pasted the translations from D6 into translated nodeblocks, and it's all set.
