### ISSUE TITLE
Spam - New users get full privs before profiles are confirmed by admins

### ISSUE THREAD

**Issue by jeanfrancoisbeaulieu** [warmshowers/Warmshowers.org#953]
Seems like upon clicking the 'enable account' link in the email you receive after sign up, you loose the 'pre-authorise' role and get a full member role.

I don't think this is the intended behavior and creates a lot of spam.

**Comment by jeanfrancoisbeaulieu** [comment]
Seems to be caused by settings on this page:

http://wsupg.dev/admin/config/people/accounts

![image](https://cloud.githubusercontent.com/assets/9020402/11159734/6cb4452a-8a30-11e5-9143-dc808e1bc666.png)

Imo, should be set to the second visitor option.

**Comment by martinmemartin** [comment]
Absolutely agree. We're getting slammed by spammers now.

**Comment by kalpaitch** [comment]
OK, if I can pause this issue because this has always been the expected behaviour, and while we need to change this behaviour we have another ticket open for this - 823 - Tempered user deletion/user cancel strategy

If we could refer to this instead for now. Thanks.
