### ISSUE TITLE
Reply-by-email should be noted on the site

### ISSUE THREAD

**Issue by chreekat** [warmshowers/Warmshowers.org#989]
For instance, I just replied to a request by email, but it did not count towards my responsiveness. Looking at my list of "unanswered" requests, I see a few other similar situations.

Whether or not the content of the email shows up in the message (but it probably should?), I think that reply-by-email should not negatively impact responsiveness.

**Comment by chreekat** [comment]
I've also replied by *phone* in a couple situations — last minute requests from people who give their number in the request. Any plan for accounting for those? :) 

I suppose #485 is the best solution. I'm not even sure qualification is needed. Someone is merely "responsive" if their percentage is >50, maybe.

**Comment by kalpaitch** [comment]
I have a feeling this issue was because we were experiencing some serious issues with incoming mail around that time. The responsiveness rating should be updated by replying by mail normally.

**Comment by chreekat** [comment]
Indeed. Now the only ones listed as no-response are the ones I responded to via phone. Heh.

**Comment by kalpaitch** [comment]
Thanks for confirming.
